year:2015
district:1
Brian Scott Willhite,8562,libertarian
Eric A. "Rick" Crawford,124139,republican
Jackie McPherson,63555,democrat
district_end
district:2
Patrick Henry Hays,103477,democrat
Debbie Standiford,10590,libertarian
<write in>,190,none
French Hill,123073,republican
district_end
district:3
Grant Brand,39305,libertarian
Steve Womack,151630,republican
district_end
district:4
James Lee Witt,87742,democrat
Bruce Westerman,110789,republican
Ken Hamilton,7598,libertarian
<write in>,2,none
district_end
year_end
year:1997
district:3
Asa Hutchinson,137093,republican
Ann Henry,102994,democrat
Tony Joe Huffman,5974,reform
Dan Ivy,71,none
district_end
district:4
Jay Dickey,125956,republican
Vincent Tolliver,72391,democrat
district_end
district:1
Marion Berry,105280,democrat
Warren Dupwe,88436,republican
Keith Carle,5734,reform
district_end
district:2
Bud Cummins,104548,republican
Vic Snyder,114841,democrat
district_end
year_end
year:2005
district:4
Mike Ross,1,democrat
district_end
district:2
Vic Snyder,160834,democrat
Marvin Parks,115655,republican
William Gabriel,4,none
district_end
district:3
John Boozman,160629,republican
Jan Judy,103158,democrat
Dale Morfey,7016,independent
district_end
district:1
Vernon Humphrey,81556,republican
Marion Berry,162388,democrat
district_end
year_end
year:2013
district:2
Tim Griffin,158175,republican
Herb Rule,113156,democrat
Chris Hayes,6701,libertarian
Barbara Ward,8566,green
district_end
district:4
Tom Cotton,154149,republican
J. Joshua Drake,4807,green
Bobby Tullis,4984,libertarian
Gene Jeffress,95013,democrat
district_end
district:1
Jessica Paxton,6427,libertarian
Jacob Holloway,5015,green
Eric A. "Rick" Crawford,138800,republican
Scott Ellington,96601,democrat
district_end
district:3
David Pangrac,19875,libertarian
Steve Womack,186467,republican
Rebekah J. Kennedy,39318,green
district_end
year_end
year:1999
district:4
Judy Smith,68194,democrat
Jay Dickey,92346,republican
district_end
district:2
Vic Snyder,100334,democrat
Phil Wyrick,72737,republican
district_end
district:3
Asa Hutchinson,154780,republican
Ralph Forbes,36917,reform
district_end
district:1
Marion Berry,1,democrat
district_end
year_end
year:2017
district:2
<write in>,303,none
J. French Hill,176472,republican
Chris Hayes,14342,libertarian
Dianne Curry,111347,democrat
district_end
district:3
Steve Womack,217192,republican
Steve Isaacson,63715,libertarian
district_end
district:1
Mark West,57181,libertarian
Eric A. "Rick" Crawford,183866,republican
district_end
district:4
Kerry Hicks,61274,libertarian
Bruce Westerman,182885,republican
district_end
year_end
year:2011
district:1
<write in>,9,none
Rick Crawford,93224,republican
Chad Causey,78267,democrat
Mickey Higgins,196,none
Ken Adler,8320,green
district_end
district:2
Lewis Kennedy,3599,green
Danial Suits,14,none
Joyce Elliott,80687,democrat
<write in>,40,none
Tim Griffin,122091,republican
Lance Levi,4421,independent
district_end
district:4
Josh Drake,4129,green
Mike Ross,102479,democrat
Beth Anne Rankin,71526,republican
district_end
district:3
Steve Womack,148581,republican
David Whitaker,56542,democrat
district_end
year_end
year:2009
district:3
Abel Noah Tomlinson,58850,green
John Boozman,215196,republican
district_end
district:2
Vic Snyder,212303,democrat
Danial Suits,665,none
Deb McFarland,64398,green
district_end
district:4
Mike Ross,203178,democrat
Joshua Drake,32603,green
district_end
district:1
Marion Berry,1,democrat
district_end
year_end
year:2001
district:2
Vic Snyder,126957,democrat
Bob Thomas,93692,republican
district_end
district:3
Asa Hutchinson,1,republican
district_end
district:1
<write in>,253,none
Susan Myshka,79437,republican
Marion Berry,120266,democrat
district_end
district:4
Mike Ross,108143,democrat
Jay Dickey,104017,republican
district_end
year_end
year:2007
district:3
John Boozman,125039,republican
Woodrow Anderson,75885,democrat
district_end
district:2
Vic Snyder,124871,democrat
Andy Mayberry,81432,republican
district_end
district:1
Marion Berry,127577,democrat
Mickey ÂÂStubbyÂÂ Stumbaugh,56611,republican
district_end
district:4
Mike Ross,128236,democrat
Joe Ross,43360,republican
district_end
year_end
year:2003
district:3
George N. Lyne,1577,none
John Boozman,141478,republican
district_end
district:1
Tommy Robinson,64357,republican
Marion Berry,129701,democrat
district_end
district:2
Ed Garner,10874,none
Vic Snyder,142752,democrat
district_end
district:4
Jay Dickey,77904,republican
Mike Ross,119633,democrat
district_end
year_end
