year:2011
district:2
Henry Raibourn,7,none
Stephen Bailey,98171,republican
Jenna Goss,7080,american constitution
Curtis Harris,5056,libertarian
Jared Polis,148720,democrat
district_end
district:4
Cory Gardner,138634,republican
Betsy Markey,109249,democrat
Doug Aden,12312,american constitution
Ken "Wasko" Waszkiewicz,3986,unaffiliated
district_end
district:5
Doug Lamborn,152829,republican
Brian "Barron X" Scott,5886,american constitution
Kevin Bradley,68039,democrat
Jerell Klaver,5680,libertarian
district_end
district:3
Scott R. Tiptin,129257,republican
Gregory Gilman,5678,libertarian
John W. Hargis, Sr.,23,none
James Fritz,11,none
Jake Segrest,4982,unaffiliated
John T. Salazar,118048,democrat
district_end
district:1
Mike Fallon,59747,republican
Clint Jones,2867,libertarian
Gary Swing,2923,green
Diana DeGette,140073,democrat
Chris Styskal,2141,american constitution
district_end
district:7
Ed Perlmutter,112667,democrat
Buck Bailey,10117,libertarian
Ryan Frazier,88026,republican
district_end
district:6
John Flerlage,104104,democrat
Michael Shawn Kearns,5,none
Mike Coffman,217368,republican
Rob McNealy,9466,libertarian
district_end
year_end
year:2013
district:5
Misha Luzov,18284,green
Jim Pirtle,22778,libertarian
Dave Anderson,53318,none
Doug Lamborn,199639,republican
Kenneth R. Harvell,13212,american constitution
district_end
district:3
Sal Pace,142619,democrat
Tisha T. Casida,11125,none
Scott R. Tipton,185291,republican
Gregory Gilman,8212,libertarian
district_end
district:7
Ed Perlmutter,182460,democrat
Buck Bailey,9148,libertarian
Joe Coors,139066,republican
Douglas ??Dayhorse?? Campbell,10296,american constitution
district_end
district:6
Patrick E. Provost,8597,libertarian
Kathy Polhemus,13442,none
Mike Coffman,163938,republican
Joe Miklosi,156937,democrat
district_end
district:4
Josh Gilliland,10682,libertarian
Brandon Shaffer,125800,democrat
Doug Aden,5848,american constitution
Cory Gardner,200006,republican
district_end
district:2
Randy Luallin,13770,libertarian
Jared Polis,234758,democrat
Susan P. Hall,10413,green
Kevin Lundberg,162639,republican
district_end
district:1
Gary Swing,4829,green
Diana DeGette,237579,democrat
Danny Stroud,93217,republican
Frank Atwood,12585,libertarian
district_end
year_end
year:2005
district:5
Fred Hardee,74098,democrat
Arthur "Rob" Roberts,6627,libertarian
Joel Hefley,193333,republican
district_end
district:6
Joanna L. Conti,139870,democrat
Jack J. Woehr,3857,libertarian
Peter Shevchuk,1236,american constitution
Thomas G. Tancredo,212778,republican
district_end
district:2
Mark Udall,207900,democrat
Stephen M. Hackman,94160,republican
Norm Olson,7304,libertarian
district_end
district:4
Marilyn N. Musgrave,155958,republican
Bob Kinsey,12739,green
Stan Matsunaka,136812,democrat
district_end
district:7
Dave Thomas,106026,democrat
Clyde J. Harkins,6167,american constitution
Bob Beauprez,135571,republican
district_end
district:3
Jim Krug,8770,unaffiliated
John Salazar,153500,democrat
Greg Walcher,141376,republican
district_end
district:1
Diana DeGette,177077,democrat
George C. Lilly,5193,american constitution
Roland Chicas,58659,republican
district_end
year_end
year:2001
district:5
Joel Hefley,253330,republican
Kerry Kantor,37719,libertarian
Randy MacKenzie,15260,natural law
district_end
district:1
Jesse L. Thomas,56291,republican
Lyle Nasser,2452,reform
<write in>,8,none
Diana DeGette,141831,democrat
Richard Combs,5852,libertarian
district_end
district:6
Thomas G. Tancredo,141410,republican
Adam D. Katz,6885,libertarian
John Heckman,3614,concerns of people
Kenneth A. Toltz,110568,democrat
district_end
district:4
Dan Sewell Ward,19721,natural law
<write in>,4539,none
Kordon L. Baker,19713,libertarian
Bob Schaffer,209078,republican
Leslie J. Hanks,9955,american constitution
district_end
district:3
Victor A. Good,5433,reform
Scott McInnis,199204,republican
Drew Sakson,9982,libertarian
Curtis Imrie,87921,democrat
district_end
district:2
Ronald N. Forthofer,12398,green
David M. Baker,5655,libertarian
Mark Udall,155725,democrat
Carolyn Cox,109338,republican
district_end
year_end
year:2009
district:4
Marilyn N. Musgrave,146028,republican
Betsy Markey,187347,democrat
district_end
district:1
George C. Lilly,67345,republican
Gary Swing,11,unaffiliated
Diana DeGette,203755,democrat
Martin L. Buchanan,12135,libertarian
district_end
district:3
John T. Salazar,203455,democrat
Wayne Wolf,126762,republican
district_end
district:5
Brian X. Scott,8894,american constitution party
Hal Bidlack,113025,democrat
Rich Hand,45,unaffiliated
Doug Lamborn,183178,republican
district_end
district:7
John W. Lerew,100055,republican
Ed Perlmutter,173931,democrat
district_end
district:6
Hank Eng,162639,democrat
Mike Coffman,250877,republican
district_end
district:2
William Robert "Bill" Hammons,2176,unity party of america
Scott Starin,116591,republican
Jared Polis,215571,democrat
J. A. Calhoun,10026,green
district_end
year_end
year:2015
district:3
Travis Mero,6472,libertarian
Tisha T. Casida,11294,unaffiliated
Scott R. Tipton,163011,republican
Abel J. Tapia,100364,democrat
district_end
district:1
Logan Blackburn,1,none
Daniel Kirschler,2,none
Martin Walsh,80682,republican
Frank Atwood,9292,libertarian
Diana DeGette,183281,democrat
Danny E. Stroud,5236,unaffiliated
district_end
district:4
Vic Meyers,83727,democrat
Grant Doherty,8016,unaffiliated
Jess Loban,9472,libertarian
Ken Buck,185292,republican
district_end
district:6
Norm Olsen,8623,libertarian
Mike Coffman,143467,republican
Gary Swing,5503,green
Andrew Romanoff,118847,democrat
district_end
district:7
Don Ytterberg,120918,republican
Ed Perlmutter,148225,democrat
district_end
district:5
Irv Halter,105673,democrat
Doug Lamborn,157182,republican
district_end
district:2
George Leing,149645,republican
Jared Polis,196300,democrat
district_end
year_end
year:2007
district:7
Rick OÂDonnell,79571,republican
Dave Chandler,3073,green
Steve Moore,2,democrat
John David Sexton,1,none
Roger McCarville,2605,constitution
Ed Perlmutter,103918,democrat
John Heckman,2,concerns of the people
district_end
district:5
Richard D. Hand,41,republican
Gregory S. Hollister,8,republican
Jay Fawcett,83431,democrat
Doug Lamborn,123264,republican
Brian X. Scott,12,democrat
district_end
district:1
Thomas D. Kelly,32825,green
Diana DeGette,129446,democrat
district_end
district:2
Norm Olsen,5025,libertarian
Rich Mancuso,65481,republican
J. A. Calhoun,2951,green
Mark Udall,157850,democrat
district_end
district:3
John T. Salazar,146488,democrat
Bruce E. Lohmiller,23,green
Scott Tipton,86930,republican
Bert L. Sargent,4417,libertarian
district_end
district:4
Eric Eidsness,27133,reform
Angie Paccione,103748,democrat
Marilyn N. Musgrave,109732,republican
district_end
district:6
Jack J. Woehr,4093,libertarian
Juan B. Botero,25,republican
Thomas G. Tancredo,158806,republican
Bill Winter,108007,democrat
district_end
year_end
year:2017
district:4
Ken Buck,248230,republican
Bruce Griffith,18761,libertarian
Bob Seay,123642,democrat
district_end
district:3
Gaylon Kent,18903,libertarian
Scott R. Tipton,204220,republican
Gail Schwartz,150914,democrat
district_end
district:5
Doug Lamborn,225445,republican
Misty Plowright,111676,democrat
Mike McRedmond,24872,libertarian
district_end
district:1
Diana DeGette,257254,democrat
Darrell Dinges,16752,libertarian
Charles "Casper" Stockham,105030,republican
district_end
district:2
Jared Polis,260175,democrat
Richard Longstreth,27136,libertarian
Nicholas Morse,170001,republican
district_end
district:7
Ed Perlmutter,199758,democrat
Martin L. Buchanan,18186,libertarian
George Athanasopoulos,144066,republican
district_end
district:6
Mike Coffman,191626,republican
Norm Olsen,18778,libertarian
Morgan Carroll,160372,democrat
Robert Lee Worthey,5641,green
district_end
year_end
year:1999
district:6
Henry L. Strauss,82662,democrat
George E. Newman,5152,natural law
Tom Tancredo,111374,republican
district_end
district:4
Bob Schaffer,131318,republican
Susan Kirkpatrick,89973,democrat
district_end
district:5
Ken Alford,55609,democrat
Joel Hefley,155790,republican
Mark A. Mellot,2871,natural law
district_end
district:3
Robert Reed Kelley,74479,democrat
Scott McInnis,156501,republican
Barry Maggert,5673,libertarian
district_end
district:2
Bob Greenlee,108385,republican
Patrick C. West,6111,natural law
Mark Udall,113946,democrat
district_end
district:1
Richard Combs,5225,libertarian
Nancy McClanahan,52452,republican
Diana DeGette,116628,democrat
district_end
year_end
year:1997
district:4
Wes McKinley,7428,americans
Bob Schaffer,137012,republican
Guy Keller,92837,democrat
Cynthia Parker,6790,natural law
district_end
district:3
Albert L. Gurule,82953,democrat
Scott McInnis,183523,republican
district_end
district:5
Joel Hefley,188805,republican
Mike Robinson,73660,democrat
district_end
district:2
Larry E. Johnson,6304,reform
David E. Skaggs,145894,democrat
Patricia (Pat) Miller,97865,republican
W. Earl Allen,5721,libertarian
district_end
district:6
Dan Schaefer,146018,republican
Joan Fitz-Gerald,88600,democrat
district_end
district:1
Richard Combs,5668,libertarian
Diana DeGette,112631,democrat
Joe Rogers,79540,republican
district_end
year_end
year:2003
district:7
G. T. "Bud" Martin,2906,libertarian
Bob Beauprez,81789,republican
Stanford E. Andress,109,none
Mike Feeley,81668,democrat
Victor Good,3133,reform
Dave Chandler,3274,green
district_end
district:1
<write in>,18,none
George C. Lilly,1169,american constitution
Diana DeGette,111718,democrat
Ken Chlouber,49884,republican
Ken Seaman,3209,green
Kent Leonard,2584,libertarian
district_end
district:2
Sandy Hume,75564,republican
Norm Olsen,3579,libertarian
Mark Udall,123504,democrat
Erik J. Brauer,1258,american constitution
Patrick West,1617,natural law
district_end
district:4
Marilyn N. Musgrave,115359,republican
John Volz,7097,libertarian
Stan Matsunaka,87499,democrat
district_end
district:6
Thomas G. Tancredo,158851,none
Lance Wright,71327,democrat
Adam D. Katz,7323,libertarian
district_end
district:5
Joel Hefley,128118,republican
Biff Baker,10972,libertarian
Curtis Imrie,45587,democrat
district_end
district:3
Denis Berckefeldt,68160,democrat
Jason Alessio,106,none
J. Brent Shroyer,4370,libertarian
Scott McInnis,143433,republican
Gary Swing,1903,natural law
district_end
year_end
