year:2017
district:13
Charlie Crist,184693,democrat
David W Jolly,171149,republican
district_end
district:18
Marilyn Holloman,9,none
Brian Mast,201488,republican
Carla Spalding,12503,none
Randy Perkins,161918,democrat
district_end
district:4
Daniel Murphy,11,none
David E. Bruderly,113088,democrat
John Rutherford,287509,republican
Gary L. Koniz,9054,none
district_end
district:6
William "Bill" McCullough,151051,democrat
Ron DeSantis,213519,republican
district_end
district:19
Francis Rooney,239225,republican
Timothy John Rossano,20,none
David Byron,109,none
Robert M. Neeld,123812,democrat
district_end
district:2
Walter Dartland,102801,democrat
Antoine Edward Roberts,3,none
Rob Lapham,9395,libertarian
Neal Dunn,231163,republican
district_end
district:1
Matt Gaetz,255107,republican
Steven Specht,114079,democrat
district_end
district:23
Debbie Wasserman Schultz,183225,democrat
Don Endriss,5180,none
Lyle Milstein,3897,none
Joseph "Joe" Kaufman,130818,republican
district_end
district:7
Mike Plaskon,33,none
John L. Mica,171583,republican
Stephanie Murphy,182039,democrat
district_end
district:11
Dave Koller,124713,democrat
Daniel Webster,258016,republican
Bruce Ray Riggs,11990,none
district_end
district:21
Paul Spain,118038,republican
Lois Frankel,210606,democrat
W. Michael "Mike" Trout,7217,none
district_end
district:24
Frederica S. Wilson,0,democrat
district_end
district:5
Glo Smith,108325,republican
Al Lawson,194549,democrat
district_end
district:15
Dennis A. Ross,182999,republican
Jim Lange,135475,democrat
district_end
district:8
Corry Westbrook,127127,democrat
Bill Stinson,16951,none
Bill Posey,246483,republican
district_end
district:12
Gus M. Bilirakis,253559,republican
Robert Matthew Tager,116110,democrat
district_end
district:3
Kenneth "Ken" McGurn,136338,democrat
Ted S. Yoho,193843,republican
Tom Wells,12519,none
district_end
district:26
Jose Peixoto,16502,none
Carlos Curbelo,148547,republican
Joe Garcia,115493,democrat
district_end
district:20
Gary Stein,54646,republican
Alcee L. Hastings,222914,democrat
district_end
district:25
Alina Valdes,95319,democrat
Mario Diaz-Balart,157921,republican
district_end
district:22
Andrea Leigh McGee,138737,republican
Theodore E. Deutch,199113,democrat
district_end
district:27
Ileana Ros-Lehtinen,157917,republican
Scott Fuhrman,129760,democrat
district_end
district:9
Darren Soto,195311,democrat
Wayne Liebnitzky,144450,republican
district_end
district:16
Vern Buchanan,230654,republican
Jan Schneider,155262,democrat
district_end
district:17
April Freeman,115974,democrat
Thomas J. Rooney,209348,republican
John W. Sawyer III,13353,none
district_end
district:10
Val Demings,198491,democrat
Thuy Lowe,107498,republican
district_end
district:14
Kathy Castor,195789,democrat
Christine Quinn,121088,republican
district_end
year_end
year:2015
district:22
Paul Spain,90685,republican
Lois Frankel,125404,democrat
Raymond Schamis,7,none
district_end
district:4
Paula Moser-Bartlett,35663,no party affiliation
Ander Crenshaw,177887,republican
Gary L. Koniz,13690,no party affiliation
Deborah Katz Pueschel,13,none
district_end
district:24
Luis E. Fernandez,5487,no party affiliation
Frederica S. Wilson,129192,democrat
Dufirston Julio Neree,15239,republican
district_end
district:6
Ron DeSantis,166254,republican
David Cox,99563,democrat
district_end
district:20
Jay Bonner,28968,republican
Alcee L. Hastings,128498,democrat
district_end
district:3
Marihelen Wheeler,73910,democrat
Ted S. Yoho,148691,republican
Howard Term Limits Lawson,6208,no party affiliation
district_end
district:12
Gus M. Bilirakis,1,republican
district_end
district:11
Dave Koller,90786,democrat
Richard B. Nugent,181508,republican
district_end
district:15
Dennis A. Ross,128750,republican
Alan M. Cohn,84832,democrat
district_end
district:19
Curt Clawson,159354,republican
Ray Netherwood,6671,libertarian
Timothy J. Rossano,12,none
April Freeman,80824,democrat
district_end
district:8
Christopher L. Duncan,61,none
Bill Posey,180728,republican
Gabriel Rothblatt,93724,democrat
district_end
district:17
Will Bronson,82263,democrat
Thomas J. Rooney,141493,republican
district_end
district:1
Jim Bryan,54976,democrat
Jeff Miller,165086,republican
Mark Wichern,15281,no party affiliation
district_end
district:23
Joseph "Joe" Kaufman,61519,republican
Debbie Wasserman Schultz,103269,democrat
district_end
district:7
Wes Neuman,73011,democrat
Al Krulick,9679,no party affiliation
John L. Mica,144474,republican
district_end
district:9
Carol Platt,74963,republican
Marko Milakovich,5060,no party affiliation
Alan Grayson,93850,democrat
Leon Leo Ray,5,none
district_end
district:25
Mario Diaz-Balart,1,republican
district_end
district:16
Joe Newman,220,none
Vern Buchanan,169126,republican
Henry Lawrence,105483,democrat
district_end
district:10
Daniel Webster,143128,republican
David B. Falstad,20,none
Michael McKenna,89426,democrat
district_end
district:13
David W. Jolly,168172,republican
Lucas Overby,55318,libertarian
Michael Stephen Levinson,86,none
district_end
district:2
Luther Lee,422,none
Gwen Graham,126096,democrat
Steve Southerland II,123262,republican
district_end
district:26
Joe Garcia,78306,democrat
Carlos Curbelo,83031,republican
district_end
district:5
Glo Smith,59237,republican
Corrine Brown,112340,democrat
district_end
district:21
W. Michael Trout,575,none
Theodore E. Deutch,153395,democrat
district_end
district:18
Patrick Murphy,151478,democrat
Carl J. Domino,101896,republican
district_end
district:14
Kathy Castor,1,democrat
district_end
district:27
Ileana Ros-Lehtinen,1,republican
district_end
year_end
year:1999
district:11
Joe Chillura,46176,republican
Jim Davis,85262,democrat
district_end
district:20
Peter Deutsch,1,democrat
district_end
district:21
Lincoln Diaz-Balart,84018,republican
Patrick Cusack,28378,democrat
district_end
district:2
Allen Boyd,138440,democrat
Timothy W. Stein,6980,none
district_end
district:22
E. Clay Shaw, Jr.,1,democrat
district_end
district:8
Bill McCollum,104298,republican
Al Krulick,54245,democrat
<write in>,32,none
district_end
district:5
Jack Gargan,67147,reform
Karen L. Thurman,132005,democrat
district_end
district:1
Joe Scarborough,140525,republican
Tom Wells,663,none
district_end
district:17
Carrie P. Meek,1,democrat
district_end
district:15
David R. Golding,75654,democrat
Dave Weldon,129278,republican
district_end
district:10
C. W. Bill Young,1,republican
district_end
district:7
John L. Mica,1,republican
district_end
district:23
Alcee L. Hastings,1,democrat
district_end
district:4
Tillie W. Fowler,1,republican
district_end
district:3
Bill Randall,53530,republican
Corrine Brown,66621,democrat
district_end
district:9
Michael Bilirakis,1,republican
district_end
district:19
Robert Wexler,1,democrat
district_end
district:13
Dan Miller,1,republican
district_end
district:6
Cliff Stearns,1,republican
district_end
district:12
Charles T. Canady,1,republican
district_end
district:16
Mark Foley,1,republican
district_end
district:14
Porter J. Goss,1,republican
district_end
district:18
Ileana Ros-Lehtinen,1,republican
district_end
year_end
year:2011
district:22
Ron Klein,99804,democrat
Allen West,118890,republican
district_end
district:24
Sandra "Sandy" Adams,146129,republican
Nicholas Ruiz III,115,none
Suzanne M. Kosmas,98787,democrat
district_end
district:14
Connie Mack,188341,republican
James Lloyd Roach,74525,democrat
William Maverick St. Claire,11825,no party affiliation
district_end
district:19
Theodore E. Deutch,132098,democrat
Joe Budd,78733,republican
Stan Smilan,228,none
district_end
district:12
Randy Wilkinson,22857,tea party
Lori Edwards,87769,democrat
Dennis A. Ross,102704,republican
district_end
district:11
Kathy Castor,91328,democrat
Mike Prendergast,61817,republican
district_end
district:1
Jim Bryan,1202,none
John Krause,18253,no party affiliation
Jeff Miller,170821,republican
Joe Cantrell,23250,no party affiliation
district_end
district:15
Bill Posey,157079,republican
Shannon Roberts,85595,democrat
district_end
district:13
James T. Golden,83123,democrat
Vern Buchanan,183811,republican
district_end
district:25
Joe Garcia,61138,democrat
David Rivera,74859,republican
Craig Porter,3244,florida whig party
Roly Arrojo,4312,tea party
district_end
district:17
Frederica S. Wilson,106361,democrat
Roderick D. Vereen,17009,no party affiliation
district_end
district:6
Steve Schonberg,71632,no party affiliation
Cliff Stearns,179349,republican
district_end
district:10
C. W. Bill Young,137943,republican
Charlie Justice,71313,democrat
district_end
district:21
Mario Diaz-Balart,1,republican
district_end
district:9
Gus M. Bilirakis,165433,republican
Anita de Palma,66158,democrat
district_end
district:16
William Dean,151,none
Thomas J. Rooney,162285,republican
Jim Horn,80327,democrat
district_end
district:8
Alan Grayson,84167,democrat
Peg Dunmire,8337,tea party
Steve J. Gerritzen,11,none
Daniel Webster,123586,republican
George L. Metcalfe,4143,no party affiliation
district_end
district:23
Alcee L. Hastings,100066,democrat
Bernard Sansaricq,26804,republican
district_end
district:2
Steve Southerland,136371,republican
Allen Boyd,105211,democrat
Paul C. mcKain,7135,no party affiliation
Dianne Berryhill,5705,no party affiliation
Ray Netherwood,16,none
district_end
district:5
Richard B. "Rich" Nugent,208815,republican
James "Jim" Piccillo,100858,democrat
district_end
district:4
Deborah "Deb" Katz Pueschel,40,none
Troy D. Stanley,52540,no party affiliation
Ander Crenshaw,178238,republican
Gary L. Koniz,27,none
district_end
district:20
Clayton Schock,3,none
Stanley Blumenthal,1663,no party affiliation
Debbie Wasserman Schultz,100787,democrat
Karen Harrington,63845,republican
Robert Kunst,1272,no party affiliation
district_end
district:18
Rolando A. Banciella,46235,democrat
Ileana Ros-Lehtinen,102360,republican
district_end
district:7
Heather Beaven,83206,democrat
John L. Mica,185470,republican
district_end
district:3
Terry Martin-Back,4625,no party affiliation
Corrine Brown,94744,democrat
Micahel "Mike" Yost,50932,republican
district_end
year_end
year:2009
district:6
Tim Cunha,146655,democrat
Cliff Stearns,228302,republican
district_end
district:5
John Russell,168446,democrat
Ginny Brown-Waite,265186,republican
district_end
district:15
Frank Zilaitis,14274,no party affiliation
Bill Posey,192151,republican
Stephen Blythe,151951,democrat
Trevor Lowing,3495,no party affiliation
district_end
district:21
Lincoln Diaz-Balart,137226,republican
Raul L. Martinez,99776,democrat
district_end
district:20
Debbie Wasserman Schultz,202832,democrat
Margaret Hostetter,58958,no party affiliation
Marc Luzietti,9,none
district_end
district:14
Connie Mack,224602,republican
Robert M. Neeld,93590,democrat
Burt Sanders,54750,no party affiliation
Jeff George,4949,no party affiliation
district_end
district:10
C. W. Bill Young,182781,republican
Bob Hackworth,118430,democrat
Don Callahan,9,none
district_end
district:11
Eddie Adams Jr.,72825,republican
Kathy Castor,184106,democrat
district_end
district:17
Kendrick B. Meek,1,democrat
district_end
district:9
Andrew Pasayan,5,none
Richard O. Emmons,2042,term limits for the united states congress
John "Johnny K."Kalimnios,3394,no party affiliation
Bill Mitchell,126346,democrat
Gus M. Bilirakis,216591,republican
district_end
district:24
Gaurav Bhola,6223,no party affiliation
Tom Feeney,151863,republican
Suzanne M. Kosmas,211284,democrat
district_end
district:4
Jay McGovern,119330,democrat
Ander Crenshaw,224112,republican
district_end
district:16
Tim Mahoney,139373,democrat
Tom Rooney,209874,republican
district_end
district:2
Allen Boyd,216804,democrat
Mark Mulligan,133404,republican
Robert Ortiz,159,none
district_end
district:1
Jeff Miller,232559,republican
James "Jim" Bryan,98797,democrat
district_end
district:23
April Cook,40,none
Marion D. Thorpe Jr.,37431,republican
Alcee L. Hastings,172835,democrat
district_end
district:13
Jan Schneider,20289,no party affiliation
Vern Buchanan,204382,republican
Don Baldauf,5358,no party affiliation
Christine Jennings,137967,democrat
district_end
district:19
Robert Wexler,202465,democrat
Edward J. Lynch,83357,republican
Ben Graber,20214,no party affiliation
district_end
district:18
Ileana Ros-Lehtinen,140617,republican
Annette Taddeo,102372,democrat
district_end
district:22
Piotr Blass,6,none
Ron Klein,169041,democrat
Allen West,140104,republican
district_end
district:25
Joe Garcia,115820,democrat
Mario Diaz-Balart,130891,republican
district_end
district:8
Ric Keller,159490,republican
Alan Grayson,172854,democrat
district_end
district:3
Corrine Brown,1,democrat
district_end
district:12
Doug Tudor,137465,democrat
Adam H. Putnam,185698,republican
district_end
district:7
Faye Armitage,146292,democrat
John L. Mica,238721,republican
district_end
year_end
year:2005
district:8
Ric Keller,172232,republican
Stephen Murray,112343,democrat
district_end
district:10
Robert D. "Bob" Derry,91658,democrat
C. W. Bill Young,207175,republican
district_end
district:22
Jack McLain,5260,constitution party of florida
Don Kennedy,627,none
E. Clay Shaw, Jr.,192581,republican
Robin Rorapaugh,108258,democrat
district_end
district:25
Mario Diaz-Balart,1,republican
district_end
district:6
David E. Bruderly,116680,democrat
N. W. O'Brien,36,none
Cliff Stearns,211137,republican
district_end
district:5
Robert G. Whittel,124140,democrat
Werder,33,none
Ginny Brown-Waite,240315,republican
district_end
district:14
Robert M. Neeld,108672,democrat
Connie Mack,226662,republican
district_end
district:11
Karl M. Butts,122,none
Robert Edward Johnson,31579,libertarian
Jim Davis,191780,democrat
district_end
district:24
Tom Feeney,1,republican
district_end
district:17
Kendrick B. Meek,178690,democrat
Omari Musa,734,none
district_end
district:21
Frank J. Gonzalez,54736,libertarian
Lincoln Diaz-Balart,146507,republican
district_end
district:15
Dave Weldon,210388,republican
Simon Pristoop,111538,democrat
district_end
district:3
Johhny M. Brown,1323,none
Corrine Brown,172833,democrat
district_end
district:2
Bev Kilmer,125399,republican
Allen Boyd,201577,democrat
T. A. Frederick,11,none
district_end
district:4
Richard Grayson,1170,none
Ander Crenshaw,256157,republican
district_end
district:9
Michael Bilirakis,284035,republican
Andrew Pasayan,243,none
district_end
district:13
Jan Schneider,153961,democrat
Katherine Harris,190477,republican
district_end
district:16
Mark Foley,215563,republican
Jeff Fisher,101247,democrat
district_end
district:1
Mark S. Coutu,72506,democrat
Jeff Miller,236604,republican
district_end
district:18
Ileana Ros-Lehtinen,143647,republican
Sam Sheldon,78281,democrat
district_end
district:23
Alcee L. Hastings,1,democrat
district_end
district:20
Margaret Hostetter,81213,republican
Debbie Wasserman Schultz,191195,democrat
district_end
district:19
Robert Wexler,1,democrat
district_end
district:7
John L. Mica,1,republican
district_end
district:12
Adam H. Putnam,179204,republican
Bob Hagenmaier,96965,democrat
district_end
year_end
year:1997
district:15
John L. Byron,115981,democrat
David Golding,15355,independent
Dave Weldon,139014,republican
district_end
district:22
E. Clay Shaw Jr.,137098,republican
<write in>,3,none
Kenneth D. Cooper,84517,democrat
district_end
district:14
Jim Nolan,63842,democrat
Porter J. Goss,176992,republican
district_end
district:23
<write in>,21,none
Alcee L. Hastings,102161,democrat
Robert Paul Brown,36907,republican
district_end
district:4
Tillie K. Fowler,1,republican
district_end
district:16
Jim Stuber,98827,democrat
Mark Foley,175714,republican
district_end
district:6
<write in>,7,none
Newell O'Brien,78908,democrat
Cliff Stearns,161527,republican
district_end
district:13
<write in>,135,none
Sanford Gordon,96098,democrat
Dan Miller,173671,republican
district_end
district:19
Beverly Kennedy,99101,republican
Robert Wexler,188766,democrat
district_end
district:2
Allen Boyd,138151,democrat
<write in>,127,none
Bill Sutton,94122,republican
district_end
district:10
Henry Green,57375,democrat
C. W. Bill Young,114443,republican
<write in>,2,none
district_end
district:9
Michael Bilirakis,161708,republican
Jerry Provenzano,73809,democrat
district_end
district:1
<write in>,104,none
Kevin Beck,66495,democrat
Joe Scarborough,175946,republican
district_end
district:5
Dave Gentry,100051,republican
Karen L. Thurman,161050,democrat
district_end
district:7
John L. Mica,143667,republican
George Stuart Jr.,87832,democrat
<write in>,58,none
district_end
district:8
<write in>,17,none
Bill McCollum,136515,republican
Al Krulick,65794,democrat
district_end
district:21
Lincoln Diaz-Balart,125469,republican
<write in>,4,none
district_end
district:18
<write in>,6,none
Ileana Ros-Lehtinen,123659,republican
district_end
district:17
Carrie P. Meek,114638,democrat
Wellington Rolle,14525,republican
<write in>,2,none
district_end
district:20
Peter Deutsch,159256,democrat
Jim Jacobs,85777,republican
district_end
district:11
Mark Sharpe,78881,republican
Jim Davis,108522,democrat
district_end
district:12
Charles T. Canady,122584,republican
Mike Canady,76513,democrat
district_end
district:3
Corrine Brown,98085,democrat
Preston James Fields,62196,republican
district_end
year_end
year:2007
district:16
Joe Negron,111415,republican
Tim Mahoney,115832,democrat
Emmie Ross,6526,none
district_end
district:12
Adam H. Putnam,124452,republican
Joe Viscusi,34976,none
Ed Bowlin,20636,none
district_end
district:13
Vern Buchanan,119309,republican
Christine Jennings,118940,democrat
district_end
district:4
Ander Crenshaw,141759,republican
John Blade,16,none
Robert J. Harms,61704,democrat
district_end
district:20
Debbie Wasserman Schultz,1,democrat
district_end
district:15
Bob Bowman,97834,democrat
Dave Weldon,125965,republican
district_end
district:25
Michael Calderin,43168,democrat
Mario Diaz-Balart,60765,republican
district_end
district:24
Tom Feeney,123795,republican
Clint Curtis,89863,democrat
district_end
district:8
D. J. Mauro,17,none
Wes Hoaglund,2640,none
Charlie Stuart,82526,democrat
Ric Keller,95258,republican
Larry Sapp,3,none
district_end
district:17
Kendrick B. Meek,90663,democrat
Eric Simpson,23,none
district_end
district:11
Kathy Castor,97470,democrat
Jim Greenwald,13,none
R. J. Spencer,5,none
Eddie Adams, Jr.,42454,republican
district_end
district:14
Robert M. Neeld,83920,democrat
Richard Grayson,3,none
Dan,1,none
Connie Mack,151615,republican
district_end
district:23
Alcee L. Hastings,1,democrat
district_end
district:10
Salvatore A. Fiorella,7,none
C. W. Bill Young,131488,republican
Samm Simpson,67950,democrat
district_end
district:18
David ÂÂBig DaveÂÂ Patlak,48499,democrat
Ileana Ros-Lehtinen,79631,republican
Margaret Trowe,2,none
district_end
district:3
Corrine Brown,1,democrat
district_end
district:2
Allen Boyd,1,democrat
district_end
district:21
Lincoln Diaz-Balart,66784,republican
Frank J. Gonzalez,45522,democrat
district_end
district:22
E. Clay Shaw, Jr.,100663,republican
Ron Klein,108688,democrat
Neil Evangelista,4254,none
district_end
district:9
Phyllis Busansky,96978,democrat
Andrew Pasayan,19,none
Gus Michael Bilirakis,123016,republican
district_end
district:7
John F. Chagnon,87584,democrat
John L. Mica,149656,republican
district_end
district:19
Robert Wexler,1,democrat
district_end
district:5
Ginny Brown-Waite,162421,republican
John Russell,108959,democrat
district_end
district:6
Cliff Stearns,136601,republican
David E. Bruderly,91528,democrat
district_end
district:1
Jeff Miller,135786,republican
Joe Roberts,62340,democrat
district_end
year_end
year:2003
district:17
Kendrick B. Meek,113749,democrat
Michael Italie,73,none
district_end
district:7
Wayne Hogan,96444,democrat
John L. Mica,142147,republican
district_end
district:11
Jim Davis,1,democrat
district_end
district:25
Mario Diaz-Balart,81845,republican
Annie Betancourt,44757,democrat
district_end
district:6
Cliff Stearns,141570,republican
David E. Bruderly,75046,democrat
district_end
district:8
Ric Keller,123497,republican
Eddie Diaz,66099,democrat
district_end
district:22
Juan Xuna,1902,no party affiliation
E. Clay Shaw Jr.,131930,republican
Carol A. Roberts,83265,democrat
Stan Smilan,18,none
district_end
district:3
Jon Arnett,4,none
Corrine Brown,88462,democrat
Jennifer Carroll,60747,republican
district_end
district:15
Jim Tso,85433,democrat
Donald Gibbens,10,none
Dave Weldon,146414,republican
district_end
district:23
B. B. B.,5,none
Charles Laurie,27986,republican
Alcee L. Hastings,96347,democrat
district_end
district:5
Jack Gargan,8639,no party affiliation
Brian Moore,6223,no party affiliation
Werder,53,none
Karen L. Thurman,117758,democrat
Ginny Brown-Waite,121998,republican
district_end
district:13
Katherine Harris,139048,republican
Jan Schneider,114739,democrat
Wayne Genthner,22,none
district_end
district:20
Peter Deutsch,1,democrat
district_end
district:1
Jeff Miller,152635,republican
Bert Oram,51972,democrat
Tom Wells,19,none
district_end
district:2
Allen Boyd,152164,democrat
Tom McGurk,75275,republican
district_end
district:4
Ander Crenshaw,171152,republican
Charles S. Knause,509,none
district_end
district:12
Adam H. Putnam,1,republican
district_end
district:18
Ileana Ros-Lehtinen,103512,republican
Orin Opperman,3423,no party affiliation
Ray Chote,42852,democrat
district_end
district:19
Robert Wexler,156747,democrat
Jack Merkl,60477,republican
district_end
district:16
Mark Foley,176171,republican
Jack McLain,47169,constitution
district_end
district:24
Tom Feeney,135576,republican
Harry Jacobs,83667,democrat
district_end
district:9
Andrew Pasayan,16,none
Chuck Kalogianis,67623,democrat
Michael Bilirakis,169369,republican
district_end
district:14
Porter J. Goss,1,republican
district_end
district:21
Lincoln Diaz-Balart,1,republican
district_end
district:10
C. W. Bill Young,1,republican
district_end
year_end
year:2013
district:7
John L. Mica,185518,republican
Jason H. Kendall,130479,democrat
Fred Marra,13,none
district_end
district:5
LeAnne Kolb,70700,republican
Eileen Fleming,7978,none
Corrine Brown,190472,democrat
Bruce Ray Riggs,3,none
district_end
district:13
C. W. Bill Young,189605,republican
Jessica Ehrlich,139742,democrat
district_end
district:26
David Rivera,108820,republican
Jose Peixoto,2717,none
Joe Garcia,135694,democrat
Angel Fernandez,5726,none
district_end
district:15
Dennis A. Ross,1,republican
district_end
district:19
Brandon M. Smith,6637,none
Trey Radel,189833,republican
Jim Roach,109746,democrat
district_end
district:4
Gary Koniz,246,none
Ander Crenshaw,239988,republican
Jim Klauder,75236,none
district_end
district:16
Keith Fitzgerald,161929,democrat
Vern Buchanan,187147,republican
district_end
district:11
H. David Werder,120303,democrat
Richard B. Nugent,218360,republican
district_end
district:23
Ilya Katz,3129,none
Karen Harrington,98096,republican
Debbie Wasserman Schultz,174205,democrat
district_end
district:20
Anthony M. Dutrow,5,none
Alcee L. Hastings,214727,democrat
Randall Terry,29553,none
district_end
district:25
Mario Diaz-Balart,151466,republican
VoteForEddie.Com,17099,none
Stanley Blumenthal,31664,none
district_end
district:3
Ted Yoho,204331,republican
J. R. Gaillot,102468,democrat
Philip Dodds,8870,none
district_end
district:17
William Bronson,116766,democrat
Tom Baumann,12,none
Thomas J. Rooney,165488,republican
district_end
district:27
Thomas Joe Cruz-Wiggins,6663,none
Ileana Ros-Lehtinen,138488,republican
Manny Yevancey,85020,democrat
district_end
district:14
Evelio ??E J?? Otero,83480,republican
Kathy Castor,197121,democrat
district_end
district:1
William Cleave Drummond II,17,none
Jim Bryan,92961,democrat
Calen Fretts,11176,libertarian
Jeff Miller,238440,republican
district_end
district:12
Gus M. Bilirakis,209604,republican
Jonathan Michael Snow,108770,democrat
John Russell,6878,none
Paul Sidney Elliott,4915,none
district_end
district:22
Adam Hasner,142050,republican
Lois Frankel,171021,democrat
district_end
district:8
Richard H. Gillmor,12607,none
Bill Posey,205432,republican
Shannon Roberts,130870,democrat
district_end
district:24
Frederica S. Wilson,1,democrat
district_end
district:2
Floyd Patrick Miller,228,none
Al Lawson,157634,democrat
Steve Southerland II,175856,republican
district_end
district:9
Alan Grayson,164891,democrat
Todd Long,98856,republican
district_end
district:21
Cesar Henao,25361,none
Theodore E. Deutch,221263,democrat
W. Michael ??Mike?? Trout,37776,none
district_end
district:6
Heather Beaven,146489,democrat
Ron Desantis,195962,republican
district_end
district:10
Daniel Webster,164649,republican
Naipaul Seegolam,46,none
Val B. Demings,153574,democrat
district_end
district:18
Allen B. West,164353,republican
Marilyn Davis Holloman,55,none
Patrick Murphy,166257,democrat
district_end
year_end
year:2001
district:17
<write in>,3,none
Carrie P. Meek,100715,democrat
district_end
district:8
Ric Keller,125253,republican
<write in>,45,none
Linda W. Chapin,121295,democrat
district_end
district:1
Joe Scarborough,226473,republican
<write in>,1066,none
district_end
district:22
Elaine Bloom,105256,democrat
<write in>,1,none
E. Clay Shaw, Jr.,105855,republican
district_end
district:14
<write in>,13,none
Sam Farling,41988,natural law
Porter J. Goss,242614,republican
district_end
district:2
Doug Dodd,71754,republican
<write in>,70,none
Allen Boyd,185579,democrat
district_end
district:3
<write in>,1,none
Corrine Brown,102143,democrat
Jennifer S. Carroll,75228,republican
district_end
district:19
Morris Kent Thompson,67789,republican
Robert Wexler,171080,democrat
district_end
district:9
Jon Duffey,46474,reform
Michael Bilirakis,210318,republican
<write in>,2,none
district_end
district:5
<write in>,16,none
Karen L. Thurman,180338,democrat
Pete Enwall,100244,republican
district_end
district:20
<write in>,187,none
Peter Deutsch,156765,democrat
district_end
district:18
<write in>,23,none
Ileana Ros-Lehtinen,112968,republican
district_end
district:23
Bill Lambert,27630,republican
Alcee L. Hastings,89179,democrat
<write in>,4,none
district_end
district:10
Josette Green,26908,natural law
C. W. Bill Young,146799,republican
Randy Heine,20296,independent
district_end
district:16
Jean Elliott Brown,108782,democrat
John McGuire,7556,reform
<write in>,9,none
Mark Foley,176153,republican
district_end
district:7
Dan Vaughen,99531,democrat
John L. Mica,171018,republican
<write in>,11,none
district_end
district:15
<write in>,1,none
Patsy Ann Kurth,117511,democrat
Gerry L Newby,5744,independent
Dave Weldon,176189,republican
district_end
district:11
Jim Davis,149465,democrat
Charlie Westlake,27197,libertarian
<write in>,21,none
district_end
district:12
Adam H. Putnam,125224,republican
Mike Stedem,94395,democrat
<write in>,6,none
district_end
district:6
Cliff Stearns,178789,republican
<write in>,31,none
district_end
district:4
Deborah Katz Pueschel,5609,independent
Tom Sullivan,94587,democrat
Ander Crenshaw,203090,republican
district_end
district:21
<write in>,25,none
Lincoln Diaz-Balart,132317,republican
district_end
district:13
<write in>,101,none
Daniel E. Dunn,99568,democrat
Dan Miller,175918,republican
district_end
year_end
