year:2001
district:3
Gail Notti,86309,democrat
Mac Collins,150200,republican
<write in>,197,none
district_end
district:1
Joyce Marie Griggs,58776,democrat
Jack Kingston,131684,republican
district_end
district:4
Sunny Warren,90277,republican
Cynthia A. McKinney,139579,democrat
district_end
district:6
Brett DeHart,86666,democrat
Johnny Isakson,256595,republican
district_end
district:7
Bob Barr,126312,republican
Roger Kahn,102272,democrat
district_end
district:9
Nathan Deal,183171,republican
James Harrington,60360,democrat
district_end
district:10
Denise Freeman,71309,democrat
Charlie Norwood,122590,republican
district_end
district:5
Hank Schwab,40606,republican
<write in>,3,none
John Lewis,137333,democrat
district_end
district:2
Sanford D. Bishop, Jr.,96430,democrat
Dylan Glenn,83870,republican
district_end
district:11
John Linder,199652,republican
district_end
district:8
Saxby Chambliss,113380,republican
Jim Marshall,79051,democrat
district_end
year_end
year:2007
district:8
Jim Marshall,80660,democrat
Mac Collins,78908,republican
district_end
district:11
Phil Gingrey,118524,republican
Patrick Samuel Pillion,48261,democrat
district_end
district:10
Charlie Norwood,117721,republican
Terry Holley,57032,democrat
district_end
district:2
Bradley C. Hughes,41967,republican
Sanford D. Bishop, Jr.,88662,democrat
district_end
district:6
Tom Price,144958,republican
Steve Sinton,55294,democrat
district_end
district:7
John Linder,130561,republican
Allan Burns,53553,democrat
district_end
district:13
Deborah Travis Honeycutt,45770,republican
David Scott,103019,democrat
district_end
district:9
John D. Bradbury,39240,democrat
Nathan Deal,128685,republican
district_end
district:12
John Barrow,71651,democrat
Max Burns,70787,republican
district_end
district:3
Mike McGraw,62371,democrat
Lynn Westmoreland,130428,republican
district_end
district:1
Jim Nelson,43668,democrat
Jack Kingston,94961,republican
district_end
district:4
Henry C. ÂÂHankÂÂ Johnson, Jr.,106352,democrat
Catherine Davis,34778,republican
district_end
district:5
John Lewis,122380,democrat
district_end
year_end
year:1997
district:10
David Bell,88054,democrat
Charlie Norwood,96723,republican
district_end
district:9
McCracken "Ken" Poston,69662,democrat
Nathan Deal,132532,republican
district_end
district:11
Tommy Stephenson,80940,democrat
John Linder,145821,republican
district_end
district:8
Jim Wiggins,84506,democrat
Saxby Chambliss,93619,republican
district_end
district:4
Cynthia A. McKinney,127157,democrat
John M. Mitnick,92985,republican
district_end
district:3
Jim Chafin,76538,democrat
Mac Collins,120251,republican
district_end
district:2
Darrel Bush Ealum,75282,republican
Sanford D. Bishop Jr.,88256,democrat
district_end
district:7
Charlie Watts,81765,democrat
Bob Barr,112009,republican
district_end
district:6
Michael Coles,127135,democrat
Newt Gingrich,174155,republican
district_end
district:5
John Lewis,136555,democrat
district_end
district:1
Rosemary D. Kaszans,50622,democrat
Jack Kingston,108616,republican
district_end
year_end
year:2011
district:11
Phil Gingrey,163515,republican
district_end
district:12
Raymond McKinney,70938,republican
John Barrow,92459,democrat
district_end
district:6
Sean Greenberg,188,none
Tom Price,198100,republican
district_end
district:10
Russell Edwards,66905,democrat
Paul C. Broun,138062,republican
district_end
district:3
Frank Saunders,73932,democrat
Jagdish Agrawal,3,none
Lynn A. Westmoreland,168304,republican
district_end
district:9
Tom Graves,173512,republican
district_end
district:7
Doug Heckmann,78996,democrat
Rob Woodall,160898,republican
district_end
district:1
Oscar L. Harris II,46449,democrat
Jack Kingston,117270,republican
district_end
district:4
Lisbeth "Liz" Carter,44707,republican
Henry C. "Hank" Johnson, Jr.,131760,democrat
district_end
district:13
David Scott,140294,democrat
Mike Crane,61771,republican
district_end
district:2
Mike Keown,81673,republican
Sanford D. Bishop, Jr.,86520,democrat
district_end
district:5
Fenn Little,46622,republican
John Lewis,130782,democrat
district_end
district:8
Austin Scott,102770,republican
Jim Marshall,92250,democrat
district_end
year_end
year:2017
district:11
Barry Loudermilk,217935,republican
Don Wilson,105383,democrat
district_end
district:1
Nathan Russo,869,none
Earl L. "Buddy" Carter,210243,republican
district_end
district:7
Rashid Malik,114220,democrat
Rob Woodall,174081,republican
district_end
district:6
Rodney Stooksbury,124917,democrat
Tom Price,201088,republican
district_end
district:8
Austin Scott,173983,republican
James Neal Harris,83225,democrat
district_end
district:14
Tom Graves,216743,republican
district_end
district:2
Sanford D. Bishop, Jr.,148543,democrat
Greg Duke,94056,republican
district_end
district:9
Doug Collins,256535,republican
district_end
district:12
Rick W. Allen,159492,republican
Patricia C. McCracken,99420,democrat
district_end
district:10
Patrick A. Boggs,210,none
Jody B. Hice,243725,republican
Leonard Ware,886,none
district_end
district:4
Henry C. "Hank" Johnson, Jr.,220146,democrat
Victor Armendariz,70593,republican
district_end
district:5
Douglas Bell,46768,republican
John Lewis,253781,democrat
district_end
district:13
David Scott,252833,democrat
district_end
district:3
Angela Pendley,95969,democrat
Drew Ferguson,207218,republican
district_end
year_end
year:2013
district:14
Daniel ??Danny?? Grant,59245,democrat
Tom Graves,159947,republican
district_end
district:4
J. Chris Vaughn,75041,republican
Henry C. ??Hank?? Johnson, Jr.,208861,democrat
district_end
district:2
John House,92410,republican
Sanford D. Bishop, Jr.,162751,democrat
district_end
district:7
Rob Woodall,156689,republican
Steve Reilly,95377,democrat
district_end
district:9
Doug Collins,192101,republican
Jody Cooley,60052,democrat
district_end
district:11
Phil Gingrey,196968,republican
Patrick Thompson,90353,democrat
district_end
district:5
Howard Stopeck,43335,republican
John Lewis,234330,democrat
district_end
district:1
Lesli Rae Messinger,92399,democrat
Jack Kingston,157181,republican
district_end
district:8
Austin Scott,197789,republican
district_end
district:3
Lynn A. Westmoreland,232380,republican
district_end
district:13
David Scott,201988,democrat
S. Malik,79550,republican
district_end
district:6
Jeff Kazanow,104365,democrat
Tom Price,189669,republican
district_end
district:10
Paul C. Broun,211065,republican
district_end
district:12
Lee Anderson,119973,republican
John Barrow,139148,democrat
district_end
year_end
year:2003
district:9
Barry Irwin,45974,democrat
Charlie Norwood,123313,republican
district_end
district:13
David Scott,70011,democrat
Clay Cox,47405,republican
district_end
district:11
Roger Kahn,65007,democrat
Phil Gingrey,69427,republican
district_end
district:4
Cynthia Van Auken,35202,republican
Denise L. Majette,118045,democrat
district_end
district:6
Johnny Isakson,163525,republican
Jeff Weisberger,41204,democrat
district_end
district:10
Nathan Deal,129242,republican
district_end
district:1
Jack Kingston,103661,republican
Don Smart,40026,democrat
district_end
district:12
Champ Walker,62904,democrat
Max Burns,77479,republican
district_end
district:8
Mac Collins,142505,republican
A. Petrakopoulos,39422,democrat
district_end
district:2
Sanford D. Bishop Jr.,102925,democrat
district_end
district:7
John Linder,138997,republican
Mike Berlon,37124,democrat
district_end
district:5
John Lewis,116259,democrat
district_end
district:3
Calder Clay,73866,republican
Jim Marshall,75394,democrat
district_end
year_end
year:2005
district:7
John Linder,258982,republican
district_end
district:11
Rick Crawford,89591,democrat
Phil Gingrey,120696,republican
district_end
district:3
Jim Marshall,136273,democrat
Calder Clay,80435,republican
district_end
district:12
John Barrow,113036,democrat
Max Burns,105132,republican
district_end
district:9
Bob Ellis,68462,democrat
Charlie Norwood,197869,republican
district_end
district:8
Lynn Westmoreland,227524,republican
Silvia Delamar,73632,democrat
district_end
district:6
<write in>,77,none
Tom Price,267542,republican
district_end
district:5
John Lewis,201773,democrat
district_end
district:13
David Scott,170657,democrat
district_end
district:4
Cynthia McKinney,157461,democrat
Catherine Davis,89509,republican
district_end
district:2
Sanford D. Bishop, Jr.,129984,democrat
Dave Eversman,64645,republican
district_end
district:1
Jack Kingston,188347,republican
district_end
district:10
Nathan Deal,219136,republican
district_end
year_end
year:2009
district:4
Henry C. "Hank" Johnson Jr.,224494,democrat
Loren Christopher Collins,159,none
Faye Coffield,35,none
Jacob Perasso,6,none
district_end
district:3
Loretta VanPelt,3,none
Lynn A. Westmoreland,225055,republican
Stephen Camp,117522,democrat
district_end
district:10
Paul C. Broun,177265,republican
Bobby Saxon,114638,democrat
district_end
district:5
Jeanne Fitzmaurice,25,none
Shira Kash,81,none
John Lewis,231368,democrat
district_end
district:2
Sanford D. Bishop Jr.,158435,democrat
Lee Ferrell,71351,republican
district_end
district:13
Deborah Honeycutt,92320,republican
David Scott,205919,democrat
district_end
district:12
John Barrow,164562,democrat
John Stone,84773,republican
district_end
district:11
Hugh "Bud" Gammon,95220,democrat
Phil Gingrey,204082,republican
district_end
district:6
Bill Jones,106551,democrat
Tom Price,231520,republican
district_end
district:7
John Linder,209354,republican
Doug Heckman,128159,democrat
district_end
district:8
Rick Goddard,117446,republican
Jim Marshall,157241,democrat
district_end
district:9
Nathan Deal,217493,republican
Jeff Scott,70537,democrat
district_end
district:1
Jack Kingston,165890,republican
Bill Gillespie,83444,democrat
district_end
year_end
year:2015
district:12
R. W. "Rick" Allen,91336,republican
John Barrow,75478,democrat
district_end
district:7
Thomas D. Wright,60112,democrat
Rob Woodall,113557,republican
district_end
district:6
Robert G. Montigel,71486,democrat
Tom Price,139018,republican
district_end
district:8
Ronald L. Cain,119,none
Austin Scott,129938,republican
district_end
district:2
Gregory P. "Greg" Duke,66537,republican
Sanford D. Bishop Jr.,96363,democrat
district_end
district:1
Brian Corwin Reese,61175,democrat
E. L. "Buddy" Carter,95337,republican
district_end
district:10
I. K. "Kenneth" Dious,65777,democrat
Jody B. Hice,130703,republican
district_end
district:4
Raymond L. Davis,109,none
Henry C. "Hank" Johnson Jr.,161211,democrat
district_end
district:9
Doug Collins,146059,republican
David D. Vogel,34988,democrat
district_end
district:14
Tom Graves,118782,republican
district_end
district:3
Lynn A. Westmoreland,156277,republican
district_end
district:11
Barry D. Loudermilk,161532,republican
district_end
district:13
David Scott,159445,democrat
district_end
district:5
John Lewis,170326,democrat
district_end
year_end
year:1999
district:6
Newt Gingrich,164966,republican
Gary "Bats" Pelphrey,68366,democrat
district_end
district:3
Mac Collins,123064,republican
district_end
district:8
Saxby Chambliss,87993,republican
Ronald L. Cain,53079,democrat
district_end
district:11
Vincent Littman,53510,democrat
John Linder,120909,republican
district_end
district:5
John Lewis,109177,democrat
John H. Lewis, Sr.,29877,republican
district_end
district:2
Joseph Francis McCormick, Jr.,59305,republican
Sanford D. Bishop, Jr.,77953,democrat
district_end
district:9
Nathan Deal,122713,republican
district_end
district:4
Cynthia A. McKinney,100622,democrat
<write in>,4,none
Sunny J. Warren,64146,republican
district_end
district:7
James F. "Jim" Williams,69293,democrat
Bob Barr,85982,republican
district_end
district:1
Jack Kingston,92229,republican
district_end
district:10
Charlie Norwood,88527,republican
Marion Denise Spencer Freeman,60004,democrat
district_end
year_end
