year:2013
district:4
Scott Soffen,6204,libertarian
Donna F. Edwards,240385,democrat
<write in>,363,none
Faith M. Loudon,64560,republican
district_end
district:8
George Gluck,5064,green
Ken Timmerman,113033,republican
Chris Van Hollen,217531,democrat
<write in>,393,none
Mark Grannis,7235,libertarian
district_end
district:1
Muir Wayne Boda,12857,libertarian
Andy Harris,214204,republican
Douglas Dryden Rae,26,none
John LaFerla,14858,democrat
Wendy Rosen,92812,democrat
Michael Calpino,71,none
<write in>,2932,none
district_end
district:5
Bob Auerbach,5040,green
Tony O?Donnell,95271,republican
Steny H. Hoyer,238618,democrat
<write in>,388,none
Arvin Vohra,4503,libertarian
district_end
district:2
C. A. Dutch Ruppersberger,194088,democrat
Leo Wayne Dymowski,9344,libertarian
Ray Bly,22,republican
Nancy C. Jacobs,92071,republican
<write in>,415,none
district_end
district:3
Eric Delano Knowles,94549,republican
John P. Sarbanes,213747,democrat
Paul W. Drgos, Jr.,11028,libertarian
<write in>,535,none
district_end
district:7
Frank C. Mirabile,67405,republican
Ronald M. Owens-Bey,8211,libertarian
Elijah E. Cummings,247770,democrat
<write in>,394,none
Charles U. Smith,28,democrat
Ty Glen Busch,10,democrat
district_end
district:6
John Delaney,181921,democrat
<write in>,399,none
Nickolaus Mueller,9916,libertarian
Roscoe G. Bartlett,117313,republican
district_end
year_end
year:2009
district:7
Charles U. Smith,8,democrat
Elijah E. Cummings,227379,democrat
Michael T. Hargadon,53147,republican
<write in>,259,none
Ronald M. Owens-Bey,5214,libertarian
Ray Bly,13,independent
district_end
district:8
Steve Hudson,66351,republican
Ian Thomas,2562,libertarian
Deborah A. Vollmer,188,democrat
Lih Young,28,democrat
<write in>,317,none
Chris Van Hollen,229740,democrat
Gordon Clark,6828,green
district_end
district:1
<write in>,329,none
Andy Harris,174213,republican
Richard James Davis,8873,libertarian
Frank M. Kratovil Jr.,177065,democrat
district_end
district:2
<write in>,408,none
Lorenzo Gaztanaga,8786,libertarian
C. A. Dutch Ruppersberger,198578,democrat
Richard Pryce Matthews,68561,republican
district_end
district:3
John P. Sarbanes,203711,democrat
Thomas E. "Pinkston" Harris,87971,republican
<write in>,766,none
district_end
district:6
Gary W. Hoover Sr.,11060,libertarian
<write in>,342,none
Jennifer P. Dougherty,128207,democrat
Roscoe G. Bartlett,190926,republican
district_end
district:5
Darlene H. Nicholas,7829,libertarian
Steny H. Hoyer,253854,democrat
Collins Bailey,82631,republican
<write in>,377,none
district_end
district:4
Steve Schulin,75,independent
Thibeaux Lincecum,3384,libertarian
Bobby Broadus,48,republican
Peter James,38739,republican
Darryn O'Shea Jackson Sr.,28,democrat
<write in>,453,none
Donna F. Edwards,258704,democrat
district_end
year_end
year:2005
district:8
Chuck Floyd,71989,republican
Lih Young,79,democrat
Chris Van Hollen,215129,democrat
district_end
district:7
Elijah E. Cummings,179189,democrat
Virginia T. Rodino,4727,green
Tony Salazar,60102,republican
district_end
district:5
Steny H. Hoyer,204867,democrat
Steve Krukar,1849,constitution
Brad Jewitt,87189,republican
Bob S. Auerbach,4224,green
district_end
district:3
Robert P. Duckworth,97008,republican
Benjamin L. Cardin,182066,democrat
Patsy Allen,7895,green
district_end
district:2
C. A. Dutch Ruppersberger,164751,democrat
Jane Brooks,75812,republican
Keith Salkowski,6508,green
district_end
district:6
Roscoe G. Bartlett,206076,republican
Gregory J. Hemingway,9324,green
Kenneth T. Bosley,90108,democrat
district_end
district:4
Albert Russell Wynn,196809,democrat
John McKinnis,52907,republican
Theresa Mitchell Dudley,11885,green
John B. Kimble,6,unaffiliated
district_end
district:1
Wayne T. Gilchrest,245149,republican
Kostas Alexakis,77872,democrat
district_end
year_end
year:2011
district:8
<write in>,224,none
Mark Grannis,2713,libertarian
Chris Van Hollen,153613,democrat
Michael Lee Philips,52421,republican
Fred Nordhorn,696,constitution
district_end
district:6
Roscoe G. Bartlett,148820,republican
<write in>,191,none
Michael Reed,5907,constitution
Andrew Duck,80455,democrat
Dan Massey,6816,libertarian
district_end
district:7
<write in>,135,none
Ray Bly,20,none
Scott Spencer,3814,libertarian
Frank Mirabile, Jr.,46375,republican
Elijah E. Cummings,152669,democrat
Fred Donald Dickson, Jr.,55,none
district_end
district:1
Michael Kennedy,18,none
Andy Harris,155118,republican
Jack N. Wilson,158,none
Frank Kratovil, Jr.,120400,democrat
Richard James Davis,10876,libertarian
<write in>,242,none
district_end
district:3
<write in>,188,none
John P. Sarbanes,147448,democrat
Jerry McKinley,5212,libertarian
Alain Lareau,1634,constitution
Jim Wilhelm,86947,republican
district_end
district:2
Marcelo Cardarelli,69523,republican
C. A. Dutch Ruppersberger,134133,democrat
<write in>,158,none
Lorenzo Gaztanaga,5090,libertarian
district_end
district:5
H. Gavin Shickle,2578,libertarian
<write in>,120,none
Steny H. Hoyer,155110,democrat
Charles Lollar,83575,republican
district_end
district:4
Robert Broadus,31467,republican
<write in>,325,none
Donna F. Edwards,160228,democrat
district_end
year_end
year:2001
district:4
<write in>,359,none
John B. Kimble,24973,republican
Albert Russell Wynn,172624,democrat
Other,13,none
district_end
district:3
<write in>,406,none
Benjamin L. Cardin,169347,democrat
Joe Pomykala,238,libertarian
Colin Harby,53827,republican
district_end
district:1
Wayne T. Gilchrest,165293,republican
Bennett Bozman,91022,democrat
David M. Gross,73,green
<write in>,294,none
district_end
district:7
<write in>,135,none
Kenneth Kondner,19773,republican
Elijah E. Cummings,134066,democrat
district_end
district:8
<write in>,275,none
Constance A. Morella,156241,republican
Brian D. Saunders,7017,constitution
Lih Young,77,democrat
Terry Lierman,136840,democrat
Scott Walker,19,other candidates
district_end
district:5
<write in>,125,none
Steny H. Hoyer,166231,democrat
Thomas E. ÂÂTimÂÂ Hutchins,89019,republican
district_end
district:6
Donald M. DeArmon,109136,democrat
<write in>,203,none
Tim McCown,82,green
Roscoe G. Bartlett,168624,republican
district_end
district:2
<write in>,285,none
Robert L. Ehrlich, Jr.,178556,republican
Kenneth T. Bosley,81591,democrat
district_end
year_end
year:2007
district:2
<write in>,215,none
C. A. Dutch Ruppersberger,135818,democrat
Jimmy Mathis,60195,republican
district_end
district:4
Michael Moshe Starkman,32792,republican
<write in>,1214,none
Albert Russell Wynn,141897,democrat
district_end
district:8
Gerard P. Giblin,3298,green
<write in>,191,none
Chris Van Hollen,168872,democrat
Jeffrey M. Stein,48324,republican
district_end
district:6
Andrew Duck,92030,democrat
Robert E. Kozak,6095,green
Roscoe G. Bartlett,141200,republican
<write in>,128,none
district_end
district:1
<write in>,232,none
Wayne T. Gilchrest,185177,republican
Jim Corwin,83738,democrat
district_end
district:3
Charles Curtis McPeek, Sr.,4941,libertarian
<write in>,229,none
John P. Sarbanes,150142,democrat
John White,79174,republican
district_end
district:5
Peter Kuhnert,635,constitution
<write in>,1110,none
Steve Warner,33464,green
Steny H. Hoyer,168114,democrat
district_end
district:7
<write in>,3147,none
Elijah E. Cummings,158830,democrat
district_end
year_end
year:2003
district:6
Roscoe G. Bartlett,147825,republican
Donald M. DeArmon,75575,democrat
district_end
district:5
Joseph T. Crawford,60758,republican
B. Auerbach,158,green
Steny H. Hoyer,137903,democrat
district_end
district:4
Floyd W. Anderson Jr.,33,none
Albert Russell Wynn,131644,democrat
Mignon Davis,162,democrat
John B. Kimble,34890,republican
district_end
district:3
Scott Conwell,75721,republican
Benjamin L. Cardin,145589,democrat
district_end
district:8
Chris Van Hollen,112788,democrat
Stephen Bassett,1599,unaffiliated
Constance A. Morella,103587,republican
district_end
district:2
Helen Delich Bentley,88954,republican
C. A. Dutch Ruppersberger,105718,democrat
district_end
district:7
Joseph E. Ward,49172,republican
Elijah E. Cummings,137047,democrat
district_end
district:1
Amy D. Tamlyn,57986,democrat
Wayne T. Gilchrest,192004,republican
district_end
year_end
year:2017
district:3
Ann Dalrymple,63,democrat
Nnabu Eze,9461,green
Mark Plaster,115048,republican
John P. Sarbanes,214640,democrat
<write in>,463,none
district_end
district:8
Dan Cox,124651,republican
Jasen Wunder,7283,libertarian
Nancy Wallace,11201,green
Kevin Levester Little,5,independent
Jamie Raskin,220657,democrat
<write in>,527,none
district_end
district:2
<write in>,592,none
C. A. Dutch Ruppersberger,192183,democrat
Kristin S. Kasprzak,14128,libertarian
Pat McDonough,102577,republican
district_end
district:6
Amie Hoeber,133081,republican
George Gluck,5824,green
<write in>,306,none
David L. Howser,6889,libertarian
Ted Athey,103,none
John K. Delaney,185770,democrat
district_end
district:4
<write in>,513,none
Benjamin Lee Krause,5744,libertarian
George E. McDermott,68670,republican
Kamesha T. Clark,8204,green
Anthony G. Brown,237501,democrat
Adrian Petrus,18,democrat
district_end
district:1
Matt Beers,15370,libertarian
Joe Werner,103622,democrat
<write in>,531,none
Andy Harris,242574,republican
district_end
district:7
Elijah E. Cummings,238838,democrat
Myles B. Hoenig,9715,green
William T. Newton,202,republican
Michael T. Pearson,17,republican
Corrogan R. Vaughn,69556,republican
<write in>,584,none
district_end
district:5
Steny H. Hoyer,242989,democrat
Mark Arness,105931,republican
Jason Summers,11078,libertarian
<write in>,636,none
district_end
year_end
year:1997
district:7
Elijah E. Cummings,115764,democrat
<write in>,2,none
Kenneth Kondner,22929,republican
district_end
district:4
Albert Russell Wynn,142094,democrat
John B. Kimble,24700,republican
district_end
district:5
John S. Morgan,91806,republican
Steny H. Hoyer,121288,democrat
district_end
district:6
<write in>,25,none
Stephen Crawford,100910,democrat
Roscoe G. Bartlett,132853,republican
district_end
district:3
Benjamin L. Cardin,130204,democrat
Patrick L. McDonough,63229,republican
district_end
district:1
<write in>,18,none
Wayne T. Gilchrest,131033,republican
Steven R. Eastaugh,81825,democrat
district_end
district:8
<write in>,379,none
Donald Mooers,96229,democrat
Constance A. Morella,152538,republican
district_end
district:2
Robert L. Ehrlich Jr.,143075,republican
Connie Galiazzo DeJuliis,88344,democrat
district_end
year_end
year:1999
district:6
Roscoe G. Bartlett,127802,republican
Timothy D. McCown,73728,democrat
district_end
district:2
Robert L. Ehrlich, Jr.,125162,republican
<write in>,9,none
Kenneth T. Bosley,74275,democrat
district_end
district:4
Albert Russell Wynn,129139,democrat
John B. Kimble,21518,republican
district_end
district:3
Colin Felix Harby,39667,republican
Benjamin L. Cardin,137501,democrat
district_end
district:8
Constance A. Morella,133145,republican
Ralph G. Neas,87497,democrat
district_end
district:1
Irving Pinder,60450,democrat
Wayne T. Gilchrest,135771,republican
district_end
district:5
Robert B. Ostrom,67176,republican
Steny H. Hoyer,126792,democrat
district_end
district:7
Kenneth Kondner,18742,republican
<write in>,1,none
Elijah E. Cummings,112699,democrat
district_end
year_end
year:2015
district:3
Other,323,none
John P. Sarbanes,128594,democrat
Charles A. Long,87029,republican
district_end
district:6
Dan Bongino,91930,republican
Other,140,none
John K. Delaney,94704,democrat
George Gluck,3762,green
district_end
district:4
Nancy Hoyt,54217,republican
Arvin Vohra,2795,libertarian
Other,197,none
Donna F. Edwards,134628,democrat
district_end
district:1
Bill Tilghman,73843,democrat
Other,233,none
Andy Harris,176342,republican
district_end
district:2
David Banach,70411,republican
Ian Schlakman,5326,green
Other,205,none
C. A. Dutch Ruppersberger,120412,democrat
district_end
district:5
Steny H. Hoyer,144725,democrat
Other,336,none
Chris Chaffee,80752,republican
Dennis L. Fritz,227,unaffiliated
district_end
district:7
Corrogan R. Vaughn,55860,republican
Elijah E. Cummings,144639,democrat
Other,207,none
Scott Soffen,6103,libertarian
district_end
district:8
Dave Wallace,87859,republican
Other,398,none
Andrew Jaye Wildman,102,none
Lih Young,16,none
Chris Van Hollen,136722,democrat
district_end
year_end
