year:2003
district:1
Steven Joyce,97931,republican
Thomas H. Allen,172646,democrat
district_end
district:2
Kevin L. Raye,107849,republican
Michael H. Michaud,116868,democrat
district_end
year_end
year:2007
district:2
Laurence S. DÂAmboise,75156,republican
Michael H. Michaud,179772,democrat
district_end
district:1
Thomas H. Allen,170949,democrat
Darlene J. Curley,88009,republican
Dexter J. Kamilewicz,22029,independent
district_end
year_end
year:2013
district:2
Kevin L. Raye,137542,republican
Michael H. Michaud,191456,democrat
Blank Vote,14910,none
district_end
district:1
Blank Vote,15912,none
Jonathan T. E. Courtney,128440,republican
Chellie Pingree,236363,democrat
district_end
year_end
year:2017
district:2
Blank Vote,12703,none
Emily Ann Cain,159081,democrat
Bruce Poliquin,192878,republican
Jay Parker Dresser,224,unenrolled
district_end
district:1
Mark I. Holbrook,164569,republican
Blank Vote,14551,none
Chellie Pingree,227546,democrat
James J. Bouchard,276,libertarian
district_end
year_end
year:1999
district:1
Eric R. Greiner,9182,taxpayers
Thomas H. Allen,134335,democrat
Ross J. Connelly,79160,republican
district_end
district:2
John Elias Baldacci,146202,democrat
Jonathan Reisman,45674,republican
district_end
year_end
year:2011
district:2
Jason J. Levesque,119669,republican
Michael H. Michaud,147042,democrat
district_end
district:1
<write in>,42,none
Dean Peter Scontras,128501,republican
Chellie Pingree,169114,democrat
district_end
year_end
year:2001
district:1
Thomas H. Allen,202823,democrat
Jane A. Amero,123915,republican
J. Frederic Staples,12356,libertarian
district_end
district:2
John E. Baldacci,219783,democrat
Richard H. Campbell,79522,republican
district_end
year_end
year:1997
district:2
Other,47,none
John Elias Baldacci,205439,democrat
Aldric Saucier,9294,independent
Paul R. Young,70856,republican
district_end
district:1
Thomas H. Allen,173745,democrat
James B. Longley Jr.,140354,republican
Other,65,none
district_end
year_end
year:2005
district:2
Michael H. Michaud,199303,democrat
Brian N. Hamel,135547,republican
Carl Cooley,8586,socialist equality
district_end
district:1
Thomas H. Allen,219077,democrat
Charles E. Summers, Jr.,147663,republican
district_end
year_end
year:2009
district:2
Michael H. Michaud,226274,democrat
John N. Frary,109268,republican
district_end
district:1
Chellie Pingree,205629,democrat
Charles E. Summers,168930,republican
district_end
year_end
year:2015
district:2
Blank Vote,11536,none
Other,248,none
Bruce Poliquin,133320,republican
Blaine Richardson,31337,independent
Emily Ann Cain,118568,democrat
district_end
district:1
Other,63,none
Chellie Pingree,186674,democrat
Blank Vote,13089,none
Richard P. Murphy,27410,independent
Isaac J. Misiuk,94751,republican
district_end
year_end
