year:2009
district:4
Gene Taylor,216542,democrat
John McCay III,73977,republican
district_end
district:1
Travis Childers,185959,democrat
Wally Pang,3736,independent
John M. Wages Jr.,1876,green
Greg Davis,149818,republican
district_end
district:2
Richard Cook,90364,republican
Bennie G. Thompson,201606,democrat
district_end
district:3
Joel Gill,127698,democrat
Gregg Harper,213171,republican
district_end
year_end
year:1997
district:5
Philip Mayeux,172,natural law
Gene Taylor,103415,democrat
Dan E. Rogers,483,libertarian
Jordan N. Gollub,429,independence
Dennis Dollar,71114,republican
Le'Roy C. Carney,1832,independent
district_end
district:2
Danny Covington,65263,republican
William G. (Will) Chipman,4167,libertarian
Bennie G. Thompson,102503,democrat
district_end
district:4
Kenneth W. Welch,2262,independence
Eileen Mahoney,1164,natural law
Mike Parker,112444,republican
Kevin Antoine,66836,democrat
William (Bill) Fausek,957,libertarian
district_end
district:1
Roger F. Wicker,123724,republican
Henry Boyd Jr.,55998,democrat
John A. (Andy) Rouse,2281,libertarian
Luke Lundemo,963,natural law
district_end
district:3
John Arthur Eaves Jr.,68658,democrat
Charles W. "Chip" Pickering Jr.,115443,republican
Charles T. Scarborough Jr.,1541,libertarian
Lamen Clemons,2502,independent
district_end
year_end
year:2013
district:2
Bennie G. Thompson,214978,none
Bill Marcy,99160,none
Cobby Mondale Williams,4605,none
Lajena Williams,1501,none
district_end
district:3
Gregg Harper,234717,none
John ??Luke?? Pannell,58605,none
district_end
district:4
Ron Williams,17982,none
Matt Moore,82344,none
Robert W. Claunch,2108,none
Steven M. Palazzo,182998,none
district_end
district:1
Danny Bedwell,3584,none
Alan Nunnelee,186760,none
Jim R. Bourland,2390,none
Brad Morris,114076,none
Chris Potts,2367,none
district_end
year_end
year:2003
district:2
Clinton B. LeSueur,69711,republican
Lee Dilworth,3426,reform
Bennie G. Thompson,89913,democrat
district_end
district:3
Harvey L. Darden,949,independent
Brad A. McDonald,760,libertarian
Carroll Grantham,498,reform
Charles W. "Chip" Pickering,139329,republican
Ronnie Shows,76184,democrat
Jim Giles,1431,independent
district_end
district:1
Roger F. Wicker,95404,republican
Brenda Blackburn,3477,reform
Rex N. Weathers,32318,democrat
Harold M. Taylor,2368,libertarian
district_end
district:4
Karl Cleveland Mertz,34373,republican
Wayne L. Parker,3311,libertarian
Thomas Huffmaster,2442,reform
Gene Taylor,121742,democrat
district_end
year_end
year:2011
district:4
Kenneth "Tim" Hampton,1741,libertarian
Steven Palazzo,105613,republican
Gene Taylor,95243,democrat
Anna Jewel Revies,787,reform
district_end
district:1
Rick "Rico" Hoskins,478,independent
Alan Nunelee,121074,republican
Les Green,2020,independent
Gail Giaramita,1235,constitution
Wally Pang,2180,independent
Barbara Dale Washer,389,reform
Harold M. Taylor,447,libertarian
Travis W. Childers,89388,democrat
A. G. Baddley,1882,independent
district_end
district:3
Tracella Lou O'Hara Hill,1586,reform
Gregg Harper,132393,republican
Jeol L. Gill,60737,democrat
district_end
district:2
Bennie G. Thompson,105327,democrat
Ashley Norwood,1530,reform
Bill Marcy,64499,republican
district_end
year_end
year:2001
district:1
Chris Lawrence,3310,libertarian
Joe T. (Joey) Grist, Jr.,59763,democrat
Roger F. Wicker,145967,republican
district_end
district:3
Charles W. ÂÂChipÂÂ Pickering,153899,republican
Jonathan Golden,2313,libertarian
William Clay Thrash,54151,democrat
district_end
district:5
Gene Taylor,153264,democrat
Randy McDonnell,35309,republican
Wayne L. Parker,3002,libertarian
Katie Perrone,2820,reform
district_end
district:4
Dunn Lampton,79218,republican
Ernie John Hopkins,2580,libertarian
Betty Pharr,1504,reform
Ronnie Shows,115732,democrat
district_end
district:2
Bennie G. Thompson,112777,democrat
William G. Chipman,4305,libertarian
Hardy Caraway,54090,republican
Lee F. Dilworth,2135,reform
district_end
year_end
year:1999
district:5
Gene Taylor,78661,democrat
Robert Claunch,1065,reform
Philip Mayeux,498,natural law
Ray Coffey,1530,libertarian
Randy McDonnell,19341,republican
district_end
district:4
Ronnie Shows,73252,democrat
Bill Fausek,898,libertarian
Delbert Hosemann,61551,republican
Vince Thornton,801,taxpayers
Kenneth Welch,697,reform
district_end
district:3
Charles T. Scarborough,15465,libertarian
Charles W. "Chip" Pickering,84785,republican
district_end
district:2
Will Chipman,32533,libertarian
Bennie G. Thompson,80284,democrat
district_end
district:1
John "Andy" Rouse,2157,libertarian
Roger F. Wicker,66738,republican
Rex Weathers,30438,democrat
district_end
year_end
year:2005
district:3
Charles W. "Chip" Pickering,234874,republican
Jim Giles,40426,independent
Lamonica L. Magee,18068,reform
district_end
district:1
Roger F. Wicker,219328,republican
Barbara Dale Washer,58256,reform
district_end
district:4
Gene Taylor,179979,democrat
Michael Lott,96740,republican
Tracella Lou O'Hara Hill,3663,reform
district_end
district:2
Shawn O'Hara,2596,reform
Clinton B. LeSueur,107647,republican
Bennie G. Thompson,154626,democrat
district_end
year_end
year:2015
district:3
Barbara Dale Washer,1541,reform
Gregg Harper,117771,republican
Douglas MacArthur "Doug" Magee,47744,democrat
Roger Gerrard,3890,independent
district_end
district:4
Matt Moore,37869,democrat
Steven M. Palazzo,108776,republican
Cindy Burleson,3684,independent
Ed Reich,857,independent
Eli "Sarge" Jackson,917,reform
Joey Robinson,3473,libertarian
district_end
district:2
Shelley Shoemake,11493,reform
Bennie G. Thompson,100688,democrat
Troy Ray,36465,independent
district_end
district:1
Alan Nunnelee,102622,republican
Lajena Walley,946,reform
Danny Bedwell,3830,libertarian
Ron E. Dickey,43713,democrat
district_end
year_end
year:2017
district:2
John Bouie II,83542,republican
Troy Ray,6918,independent
Johnny McLeod,3823,reform
Bennie G. Thompson,192343,democrat
district_end
district:1
Chase Wilson,6181,libertarian
Cathy L. Toole,3840,reform
Jacob Owens,83947,democrat
Trent Kelly,206455,republican
district_end
district:3
Gregg Harper,209490,republican
Roger I. Gerrard,8696,veterans party of america
Lajena Sheets,2158,reform
Dennis Quinn,96101,democrat
district_end
district:4
Mark Gladney,77505,democrat
Shawn O'Hara,5264,reform
Richard Blake McCluskey,14687,libertarian
Steven M. Palazzo,181323,republican
district_end
year_end
year:2007
district:1
James K. (Ken) Hurt,49174,democrat
Roger F. Wicker,95098,republican
district_end
district:2
Yvonne R. Brown,55672,republican
Bennie G. Thompson,100160,democrat
district_end
district:4
Randy McDonnell,28117,republican
Gene Taylor,110996,democrat
district_end
district:3
Jim Giles,25999,independent
Charles W. ÂÂChipÂÂ Pickering,125421,republican
Lamonica L. Magee,10060,reform
district_end
year_end
