year:2015
district:2
Alexander H. Spano,663,d-r party
William J. Hughes Jr.,66026,democrat
Costantino Rozzo,501,american labor
Frank A. LoBiondo,108875,republican
Gary Stein,612,independent
Bayode Olabisi,471,independent
district_end
district:1
Margaret M. Chapman,1103,change is needed
Robert Shapiro,1134,stop boss politics
Donald E. Letton,449,d-r party
Garry W. Cobb,64073,republican
Donald W. Norcross,93315,democrat
Mike Berman,634,of the people
Scot John Tomaszewski,1784,we deserve better
district_end
district:12
Jack Freudenheim,531,start the conversation
Alieta Eck,54168,republican
Bonnie Watson,90430,democrat
Kenneth J. Cody,567,truth vision hope
Don DeZarn,1330,legalize marijuana
Steven Welzer,890,green
Allen J. Cannon,450,d-r party
district_end
district:5
Mark D. Quick,2435,for americans
Scott Garrett,104678,republican
Roy Cho,81808,democrat
district_end
district:9
Dierdre G. Paul,36246,republican
Nestor Montilla,1715,seeking inclusion
Bill Pascrell,82498,democrat
district_end
district:10
Gwendolyn A. Franklin,1237,bullying breaks hearts
Yolanda Dentley,14154,republican
Dark Angel,998,future.vision
Donald M. Payne Jr.,95734,democrat
district_end
district:3
Frederick John LaVergne,3095,d-r party
Tom MacArthur,100471,republican
Aimee Belgard,82537,democrat
district_end
district:8
Pablo Olivera,1022,wake up usa
Jude Anthony Tiscornia,15141,republican
Herbert H. Shaw,1192,politicians are crooks
Albio Sires,61510,democrat
Robert Thorne,653,911 truth needed
district_end
district:4
Christopher H. Smith,118826,republican
Ruben M. Scolavino,54415,democrat
Scott Neuman,1608,d-r party
district_end
district:7
Leonard Lance,104287,republican
Janice Kovach,68232,democrat
James Gawron,3478,libertarian
district_end
district:6
Frank Pallone Jr.,72190,democrat
Dorit Goikhman,1376,libertarian
Anthony E. Wilkinson,46891,republican
district_end
district:11
Mark Dunec,65477,democrat
Rodney P. Frelinghuysen,109455,republican
district_end
year_end
year:1999
district:8
Matthew J. Kirnan,46289,republican
Bernard George,722,independent
Thomas Paine Caslander,625,independent
Jeffrey Levine,804,independent
Jose L. Aravena,318,independent
Stephen Spinosa,762,independent
Bill Pascrell, Jr.,81068,democrat
district_end
district:11
Rodney P. Frelinghuysen,100910,republican
John P. Scollo,44160,democrat
Stephen A. Bauer,755,indepdendent
Agnes A. James,1409,indepdendent
Austin S. Lett,1737,indepdendent
district_end
district:1
Ronald L. Richards,27855,republican
Joesph W. Stockman,1324,independent
James E. Barber,943,independent
Edward "Rob" Forchion,1257,independent
Robert E. Andrews,90279,democrat
David E. West, Jr.,1684,independent
district_end
district:3
Steven J. Polansky,55248,democrat
Ken Feduniewicz,285,indepdendent
James Pircher,608,indepdendent
Jim Saxton,97508,republican
Janice Presser,2527,indepdendent
Norman E. Wahner,1063,indepdendent
district_end
district:12
Beverly Kidder,749,independent
Joseph A. Siano,2125,independent
Michael Pappas,87221,republican
Madelyn R. Hoffman,1409,independent
Mary Jo Christian,578,independent
Rush Holt,92528,democrat
district_end
district:9
Michael Perrone, Jr.,1349,independent
Steven R. Rothman,91330,democrat
Steve Lonegan,47817,republican
Michael W. Koontz,686,independent
Kenneth Ebel,277,independent
district_end
district:6
Carl J. Mayer,1291,independent
Michael Ferguson,55180,republican
Frank Pallone, Jr.,78102,democrat
Leonard P. Marshall,1177,independent
Steve Nagle,1262,independent
district_end
district:5
Thomas W. Wright,2395,independent
Marge Roukema,106304,republican
Helen Hamilton,1004,independent
William Weightman,1628,independent
Mike Scheider,55487,democrat
district_end
district:2
Mary A. Whittam,1748,independent
Frank A. LoBiondo,93248,republican
Glenn Campbell,2955,independent
Derek Hunsberger,43563,democrat
district_end
district:13
Susan Anmuth,752,independent
Richard S. Hester, Sr.,1276,independent
Robert Menendez,70308,democrat
Theresa De Leon,14615,republican
Richard G. Rivera,872,independent
district_end
district:10
Richard J. Pezzullo,3293,independent
Maurice Williams,2279,independent
William Stanley Wnuck,10678,republican
Donald M. Payne,82244,democrat
district_end
district:4
Nick Mellis,1054,indepdendent
Larry Schneider,52281,democrat
Keith Quarles,1753,indepdendent
Morgan Strong,1498,indepdendent
Christopher H. Smith,92991,republican
district_end
district:7
Bob Franks,77751,republican
Darren Young,1508,indepdendent
Maryanne S. Connelly,65776,democrat
Richard C. Martin,3007,indepdendent
district_end
year_end
year:2003
district:7
Darren Young,2068,libertarian
Mike Ferguson,106055,republican
Tim Carden,74879,democrat
district_end
district:8
Joseph A. Fortunato,3400,green
Bill Pascrell Jr.,88101,democrat
Jared Silverman,40318,republican
district_end
district:2
Michael J. Matthews Jr.,1720,libertarian
Costantino Rozzo,771,socialist
Roger Merle,1739,green
Steven A. Farkas,47735,democrat
Frank A. LoBiondo,116834,republican
district_end
district:13
Robert Menendez,72605,democrat
Dick Hester,732,conservative
James Geron,16852,republican
Pat Henry Faulkner,1195,green
Herbert H. Shaw,573,politicians are crooks
Esmat Zaklama,34,the american party
Esmat Zaklama,740,anti-corruption doctor
district_end
district:11
Vij Pawar,48477,democrat
Richard S. Roth,2263,libertarian
Rodney P. Frelinghuysen,132938,republican
district_end
district:10
Donald M. Payne,86433,democrat
Andrew Wirtz,15913,republican
district_end
district:3
Ken Feduniewicz,665,american first
Jim Saxton,123375,republican
Richard Strada,64364,democrat
Raymond Byrne,1335,libertarian
district_end
district:5
Scott Garrett,118881,republican
Michael J. Cino,4466,lower tax independent
Anne Sumers,76504,democrat
district_end
district:12
Thomas D. Abrams,1259,libertarian
Rush D. Holt,104806,democrat
Carl J. Mayer,1871,green
DeForest "Buster" Soaries,62938,republican
Karen Anne Zaletal,839,conservative
district_end
district:1
Robert E. Andrews,121846,democrat
Timothy Haas,9543,libertarian
district_end
district:4
Christopher H. Smith,115293,republican
Hermann Winkelmann,1063,honesty, humanity, duty
Mary Brennan,55967,democrat
Keith Quarles,1211,libertarian
Don Graham,767,conservative
district_end
district:6
Richard D. Strong,1819,green
Barry Allen,1206,libertarian
Mac Dara Francis X. Lyden,612,human rights advocate
Ric Medrow,42479,republican
Frank Pallone Jr.,91379,democrat
district_end
district:9
Joseph Glass,42088,republican
Steven R. Rothman,97108,democrat
district_end
year_end
year:2011
district:4
Christopher H. Smith,129752,republican
Howard Kleinhendler,52118,democrat
Joe Siano,2912,libertarian
David R. Meiswinkle,582,american renaissance movement
Steven Welzer,1574,green
district_end
district:5
Tod Theise,62634,democrat
Mark D. Quick,1646,for americans
Scott Garrett,124030,republican
James Douglas Radigan,336,be determined
Ed Fanning,2347,green
district_end
district:10
Donald M. Payne,95299,democrat
Joanne Miller,1080,agent of change
Robert Louis Toussaint,1141,action no talk
Michael J. Alonso,14357,republican
district_end
district:11
Rodney P. Frelinghuysen,122149,republican
Jim Gawron,4179,libertarian
Douglas Herbert,55472,democrat
district_end
district:2
Mark Lovett,1123,marklovett.us
Gary Stein,51690,democrat
Vitov Valdes-Munoz,727,american labor
Peter F. Boyce,4120,constitution
Frank A. LoBiondo,109460,republican
district_end
district:3
Jon Runyan,110215,republican
John H. Alder,104252,democrat
Peter DeStefano,3284,new jersey tea party
Rudd Conger,1445,libertarian
Lawrence J. Donahue,1113,your country again
district_end
district:6
Anna C. Little,65413,republican
Frank Pallone, Jr.,81933,democrat
Karen Anne Zaletel,1017,green tea patriots
Jack Freudenheim,1299,independent
district_end
district:13
Maximo Gomez Nacer,910,gravity buoyancy solution
Henrietta Dwyer,19538,republican
Albio Sires,62840,democrat
Anthony Zanowic,1508,independent american
district_end
district:1
Nicky I. Petrutz,521,defend american constitution
Mark Heacock,1593,green
Dale Glading,58562,republican
Robert E. Andrews,106334,democrat
Margaret M. Chapman,1257,time for change
district_end
district:7
Leonard Lance,105084,republican
Ed Potosnak,71902,democrat
district_end
district:8
Raymond Giangrasso,1707,independent
Roland Straten,51023,republican
Bill Bascrell, Jr.,88478,democrat
district_end
district:9
Steven R. Rothman,83564,democrat
Michael A. Agosta,52082,republican
Patricia Alessandrini,1980,green
district_end
district:12
Scott Sipprelle,93634,republican
Kenneth J. Cody,2154,truth vision hope
Rush D. Holt,108214,democrat
district_end
year_end
year:2013
district:3
Robert Shapiro,1104,bob?s for jobs
Jon Runyan,174253,republican
Frederick John Lavergne,770,no slogan
Shelley Adler,145506,democrat
Robert Edward Forchion,1956,legalize marijuana
Robert Witterschein,530,none of them
Christopher G. Dennick, Jr.,280,no slogan
district_end
district:10
Joanne Miller,3127,change, change, change
Brian C. Kelemen,24271,republican
Donald M. Payne, Jr.,201435,democrat
Mick Erickson,1227,libertarian
district_end
district:4
Brian P. Froelich,107991,democrat
Leonard P. Marshall,3111,no slogan
Christopher H. Smith,195145,republican
district_end
district:8
Albio Sires,130853,democrat
Maria Karczewski,31763,republican
Pablo Olivera,1625,unity is strength
Stephen Deluca,1710,restoring america?s promise
Herbert H. Shaw,1839,politicians are crooks
district_end
district:6
Mac Dara Lyden,830,independent
Anna Little,84360,republican
Len Flynn,1392,libertarian
Karen Zaletel,868,overthrow all incumbents
Frank Pallone, Jr.,151782,democrat
Herbert L. Tarbous,406,reform
district_end
district:11
Rodney P. Frelinghuysen,182237,republican
John Arvanites,123897,democrat
Barry Berlin,3725,opposing congressional gridlock
district_end
district:5
Patricia Alessandrini,6770,green
Scott Garrett,167501,republican
Adam Gussen,130100,democrat
district_end
district:2
David W. Bowen, Sr.,1010,the people's agenda
Cassandra Shober,116462,democrat
John Ordille,2699,libertarian
Frank A. LoBiondo,166677,republican
Charles Lukens,1329,constitutional conservative
Frank Faralli, Jr.,892,conservative, compassionate, creative
district_end
district:1
Gregory W. Horton,92459,republican
Robert E. Andrews,210470,democrat
Margaret Chapman,1177,reform
John William Reitter,4413,green
district_end
district:9
Bill Pascrell, Jr.,162822,democrat
Shmuley Boteach,55091,republican
Jeanette Woolsey,1082,constitution
E. David Smith,1138,abundant america
district_end
district:12
Eric A. Beck,80906,republican
Kenneth J. Cody,1285,truth vision hope
Jack Freudenheim,2261,independent
Rush D. Holt,189926,democrat
district_end
district:7
Upendra J. Chivukula,123057,democrat
Patrick McKnight,4078,libertarian
Leonard Lance,175662,republican
Dennis A. Breen,4518,independent reform candidate
district_end
year_end
year:2009
district:13
Joseph Turula,34735,republican
Julio A. Fernandez,3661,no party affiliation
Albio Sires,120382,democrat
Louis Vernotico,975,eliminate the primary
district_end
district:3
John Adler,166390,democrat
Chris Meyers,153122,republican
district_end
district:1
Margaret M. Chapman,1258,back to basics
Dale M. Glading,74001,republican
Robert E. Andrews,206453,democrat
Matthew Thieke,1927,green
Everitt M. Williams III,1010,think independently
Alvin Lindsay Jr.,508,lindsay for congress
district_end
district:5
Ed Fanning,5321,green
Dennis Shulman,131033,democrat
Scott Garrett,172653,republican
district_end
district:2
David Kurkowski,110990,democrat
Jason M. Grover,1763,green
Gary Stein,1312,rock the boat
Costantino Rozzo,648,socialist
Peter F. Boyce,1551,constitution
Frank A. LoBiondo,167701,republican
district_end
district:8
Derek DeMarco,1600,libertarian
Roland Straten,63107,republican
Bill Pascrell Jr.,159279,democrat
district_end
district:11
Tom Wyka,113510,democrat
Chandler Tedholm,3526,for the people
Rodney P. Frelinghuysen,189696,republican
district_end
district:7
Linda Stender,124818,democrat
Dean Greco,3259,all-day breakfast party
Leonard Lance,148461,republican
Michael P. Hsing,16419,hsing for congress
Thomas D. Abrams,2671,prosperity not war
district_end
district:4
Christopher H. Smith,202972,republican
Steven Welzer,3543,green
Joshua M. Zeitz,100036,democrat
district_end
district:6
Frank Pallone Jr.,164077,democrat
Herb Tarbous,3531,independent
Robert E. McLeod,77469,republican
district_end
district:9
Vincent Micco,69503,republican
Steven R. Rothman,151182,democrat
Michael Perrone Jr.,3200,independent
district_end
district:12
Rush D. Holt,193732,democrat
David Corsi,4802,common sense ideas
Alan R. Bateman,108400,republican
district_end
district:10
Michael Taber,1848,socialist workers
Donald M. Payne,169945,democrat
district_end
year_end
year:2017
district:6
Judith Shamy,1720,libertarian
Rajit B. Malliah,1912,green
Frank Pallone, Jr.,167895,democrat
Brent Sonnek-Schmelz,91908,republican
district_end
district:1
Donald Norcross,183231,democrat
Bob Patterson,112388,republican
Scot John Tomaszewski,5473,socialist
Michael Berman,1971,americanindependents
William F. Sihr IV,2410,libertarian
district_end
district:2
Frank A. LoBiondo,176338,republican
David H. Cole,110838,democrat
Eric Beechwood,1387,people's independent progressive
Gabriel Brian Franco,1232,for political revolution
John Ordille,3773,libertarian
James Keenan,2653,make government work
Steven Fenichel,1574,representing the 99%
district_end
district:10
David H. Pinckney,26450,republican
Donald M. Payne, Jr.,190856,democrat
Joanne Miller,3719,women of power
Aaron Walter Fraser,1746,new beginning's
district_end
district:5
Scott Garrett,157690,republican
Joshua S. Gottheimer,172587,democrat
Claudio Belusic,7424,libertarian
district_end
district:9
Hector L. Castillo,65376,republican
Bill Pascrell, Jr.,162642,democrat
Jeff Boss,1897,nsa did 911
Diego Rivera,3327,libertarian
district_end
district:8
Albio Sires,134733,democrat
Agha Khan,32337,republican
Dan Delaney,3438,libertarian
Pablo Olivera,4381,wake up america
district_end
district:12
Steven Welzer,2135,green
Steven J. Uccio,92407,republican
Thomas Fitzpatrick,2482,libertarian
Michael R. Bollentin,1311,we the people
Bonnie Watson Coleman,181430,democrat
R. Edward Forchion,6094,legalize marijuana party
Robert Shapiro,2775,teddy roosevelt progressive
district_end
district:11
Thomas DePasquale,7056,financial independence
Jeff Hetrick,3475,libertarian
Joseph M. Wenzel,130162,democrat
Rodney P. Frelinghuysen,194299,republican
district_end
district:7
Leonard Lance,185850,republican
Peter Jacob,148188,democrat
Arthur T. Haussmann, Jr.,4254,conservative
Dan O'Neill,5343,libertarian
district_end
district:4
Lorna Phillipson,111532,democrat
Christopher H. Smith,211992,republican
Hank Schroeder,5840,economic growth
Jeremy Marcus,3320,libertarian
district_end
district:3
Frederick John Lavergne,127526,democrat
Lawrence W. Berlinski, Jr.,5938,constitution
Thomas MacArthur,194596,republican
district_end
year_end
year:1997
district:6
Steven J. Corodemus,73402,republican
Frank Pallone Jr.,124635,democrat
Susan H. Normandin,1247,independent
Keith Quarles,2044,independent
Richard Sorrentino,1509,independent
Stefanie C. Trice,641,independent
district_end
district:8
William J. Martini,92609,republican
William J. Pascrell Jr.,98861,democrat
Jeffrey M. Levine,1621,independent
district_end
district:12
David M. DelVecchio,125594,democrat
Jospeh M. Mercurio,2650,independent
Virginia A. Flynn,3955,independent
Philip G. Cenicola,1211,independent
Mike Pappas,135811,republican
district_end
district:1
Robert E. Andrews,160413,democrat
Patricia A. Bily,1873,independent
Norman E. Wahner,1493,independent
Michael Edmondson,2668,independent
Mel Suplee,44287,republican
district_end
district:5
Helen Hamilton,1678,independent
Bill Auer,62956,democrat
Lorraine L. LaNeve,4093,independent
E. Gregory Kresge,899,independent
Dan Karlan,2118,independent
Barry Childers,1266,independent
Marge Roukema,181323,republican
district_end
district:7
Nicholas W. Gentile,1693,independent
Dorothy DeLaura,4076,independent
Larry Lerner,97285,democrat
Robert G. Robertson,696,independent
Bob Franks,128821,republican
district_end
district:3
Janice Presser,3037,independent
Agnes A. James,1355,independent
John Leonardi,81590,democrat
Eugene B. Ashworth,1134,independent
Ken Feduniewicz,659,independent
Jim Saxton,157503,republican
district_end
district:13
Rupert Ravens,637,independent
Mike Buoncristiano,2094,independent
Carlos E. Munoz,25427,republican
Robert Menendez,115459,democrat
Herbert H. Shaw,2136,independent
William P. Estrada,720,independent
district_end
district:4
J. Morgan Strong,2034,independent
Arnold Kokans,1111,independent
Robert Figueroa,3000,independent
Christopher H. Smith,146404,republican
Kevin John Meara,77565,democrat
district_end
district:2
David Rodger Headrick,1439,independent
Judith Lee Azaren,1174,independent
Andrea Lippi,1084,independent
Ruth Katz,83890,democrat
Frank A. LoBiondo,133131,republican
district_end
district:10
Donald M. Payne,127126,democrat
Toni M. Jackson,656,independent
Harley Tyler,1192,independent
Vanessa Williams,22086,republican
district_end
district:9
Arthur B. Rosen,2730,independent
Kathleen A. Donovan,89005,republican
Leon Myerson,1549,independent
Steven R. Rothman,117646,democrat
district_end
district:11
Rodney P. Frelinghuysen,169091,republican
Austin S. Lett,2618,independent
Chris Evangel,78742,democrat
Ed DeMott,2870,independent
Victoria S. Spruiell,1837,independent
district_end
year_end
year:2001
district:12
John P. Desmond,1233,independent
Carl Mayer,5811,independent
Dick Zimmer,145511,republican
Rush D. Holt,146162,democrat
Worth Winslow,1225,independent
district_end
district:9
Steven R. Rothman,140462,democrat
Robert Corriston,980,independent
Michael Perrone, Jr.,1072,independent
Lewis Pell,2273,independent
Joseph Tedeschi,61984,republican
district_end
district:3
Ken Feduniewicz,948,independent
Norman E. Wahner,719,independent
Susan Bass Levin,112848,democrat
Jim Saxton,157053,republican
Aaron M. Kromash,2515,independent
district_end
district:6
Brian T. Kennedy,62454,republican
Sylvia Kuzmak,328,independent
Frank Pallone, Jr.,141698,democrat
Earl Gray,4252,independent
Karen Zaletel,1120,independent
district_end
district:5
Marge Roukema,175546,republican
Helen Hamilton,481,independent
Linda A. Mercurio,81715,democrat
Robert J. McCafferty,4095,independent
Ira W. Goodman,1358,independent
Michael ÂÂMJÂÂ King,5329,independent
district_end
district:13
Theresa de Leon,27849,republican
Alina Lydia Fonteboa,233,independent
Herbert H. Shaw,357,independent
Dick Hester,562,independent
Robert Menendez,117856,democrat
Claudette C. Meliere,2741,independent
Kari Sachs,168,independent
district_end
district:11
John Pickarski,5199,independent
Rodney P. Frelinghuysen,186140,republican
James E. Spinosa,1541,independent
John P. Scollo,80958,democrat
district_end
district:8
Anthony Fusco, Jr.,60606,republican
Joseph A. Fortunato,4469,independent
Viji Sargis,983,independent
Bill Pascrell, Jr.,134074,democrat
district_end
district:7
Darren Young,973,independent
Jerry L. Coleman,5444,independent
Mike Ferguson,128434,republican
Maryanne Connelly,113479,democrat
Mary T. Johnson,283,independent
Shawn Gianella,386,independent
district_end
district:2
Robert Gabrielsky,3252,independent
Constantino Rozzo,788,independent
Edward G. Janosik,74632,democrat
Frank A. LoBiondo,155187,republican
district_end
district:4
Paul D. Teel,712,independent
Christopher H. Smith,158515,republican
Reed Gusciora,87956,democrat
Stuart Chaifetz,3627,independent
district_end
district:1
Joseph A. Patalivo,781,independent
Robert E. Andrews,167327,democrat
Charlene Cathcart,46455,republican
Edward Forchion,1959,independent
Catherine L. Parrish,3090,independent
district_end
district:10
Dirk B. Weber,18436,republican
Maurice Williams,536,independent
Donald M. Payne,133073,democrat
district_end
year_end
year:2007
district:7
Darren Young,2046,libertarian
Mike Ferguson,98399,republican
Thomas D. Abrams,3176,withdraw troops now
Linda Stender,95454,democrat
district_end
district:2
Thomas Fanslau,603,we the people
Viola Thomas-Hughes,64277,democrat
Robert E. Mullock,3071,preserve green space
Frank A. LoBiondo,111245,republican
Willie Norwood,385,socialist party usa
Lynn Merle,992,a new direction
district_end
district:8
Lou Jasikoff,1018,libertarian
Jose M. Sandoval,39053,republican
Bill Pascrell, Jr.,97568,democrat
district_end
district:13
Brian Williams,1049,socialist workers
John J. Guarini,19284,republican
Esmat Zaklama,475,the american party
Albio Sires,77238,democrat
Dick Hester,586,pro life conservative
Herbert H. Shaw,998,politicians are crooks
district_end
district:5
Scott Garrett,112142,republican
R. Matthew Fretz,2597,an independent voice
Paul Aronsohn,89503,democrat
district_end
district:4
Richard Edgar,1539,libertarian
Louis B. Wary, Jr.,614,remove medical negligence
Christopher H. Smith,124482,republican
Carol E. Gay,62905,democrat
district_end
district:3
Ken Feduniewicz,1179,the patriot movement
Jim Saxton,122559,republican
Rich Sexton,86113,democrat
district_end
district:6
Frank Pallone, Jr.,98615,democrat
Herbert L. Tarbous,1619,diversity is strength
Leigh-Ann Bellew,43539,republican
district_end
district:12
Rush D. Holt,125468,democrat
Joseph S. Sinagra,65509,republican
district_end
district:9
Michael Jarvis,1363,the moderate choice
Vincent Micco,40879,republican
Steven R. Rothman,105853,democrat
district_end
district:11
Tom Wyka,74414,democrat
Richard S. Roth,1730,libertarian
Rodney P. Frelinghuysen,126085,republican
John Mele,842,constitution
district_end
district:10
Donald M. Payne,90264,democrat
district_end
district:1
Robert E. Andrews,140110,democrat
district_end
year_end
year:2005
district:11
James W. Buell,91811,democrat
Rodney P. Frelinghuysen,200915,republican
John Mele,1746,independent
Austin S. Lett,1530,independent
district_end
district:1
Arturo Fulvio Croce,931,independent
Robert E. Andrews,201163,democrat
S. Daniel Hutchison,66109,republican
district_end
district:4
Richard Edgar,2056,independent
Christopher H. Smith,192671,republican
Amy Vazquez,92826,democrat
district_end
district:6
Frank Pallone, Jr.,153981,democrat
Sylvester Fernandez,70942,republican
Mac Dara F. X. Lyden,2399,independent
Virginia A. Flynn,2829,independent
district_end
district:8
Joseph A. Fortunato,4072,independent
Bill Pascrell, Jr.,152001,democrat
George Ajjan,62747,republican
district_end
district:10
Toy-Ling Washington,2927,independent
Sara J. Lobman,2089,independent
Donald M. Payne,155697,democrat
district_end
district:3
Herb Conaway,107034,democrat
Frank Orland,976,independent
R. Edward Forchion,4914,independent
Jim Saxton,195938,republican
district_end
district:2
Michael J. Matthews, Jr.,1767,independent
Jose David Alcantara,1516,independent
Costantino Rozzo,595,independent
Timothy J. Robb,86792,democrat
Frank A. LoBiondo,172779,republican
Willie Norwood,1993,independent
district_end
district:12
Rush D. Holt,171691,democrat
Bill Spadea,115014,republican
Ken Chazotte,1562,independent
Daryl M. Brooks,1518,independent
district_end
district:9
David Daly,1649,independent
Edward Trawinski,68564,republican
Steven R. Rothman,146038,democrat
district_end
district:7
Steve Brozak,119081,democrat
Mike Ferguson,162597,republican
Matthew Angus Williams,2016,independent
Thomas D. Abrams,2153,independent
district_end
district:5
Thomas A. Phelan,1515,independent
Scott Garrett,171220,republican
Dorothea Anne Wolfe,122259,democrat
Victor Kaplan,1857,independent
Gregory Pason,574,independent
district_end
district:13
Herbert H. Shaw,1066,independent
Angela L. Lariscy,887,independent
Robert Menendez,121018,democrat
Dick Hester,1282,independent
Richard W. Piatkowski,35288,republican
district_end
year_end
