year:2003
district:4
Michael Oxley,120001,republican
Jim Clark,57726,democrat
district_end
district:10
Jon A. Heben,41778,republican
Judy Locy,3761,independent
Dennis J. Kucinich,129997,democrat
district_end
district:2
James Condit Jr.,13,none
Charles Sanders,48785,democrat
Rob Portman,139218,republican
district_end
district:1
Greg Harris,60168,democrat
Steve Chabot,110760,republican
district_end
district:9
Marcy Kaptur,132236,democrat
Ed Emery,46481,republican
district_end
district:13
Sherrod Brown,123025,democrat
Ed Oliveros,55357,republican
district_end
district:8
John A. Boehner,119947,republican
Jeff Hardenbrook,49444,democrat
district_end
district:3
Michael R. Turner,111630,republican
Rick Carne,78307,democrat
Ronald Williamitis,14,independent
district_end
district:18
Robert W. Ney,125546,republican
district_end
district:7
David L. Hobson,113252,republican
Kara Anastasio,45568,democrat
Frank Doden,8812,independent
district_end
district:15
Mark Brown,54286,democrat
Deborah Pryce,108193,republican
district_end
district:17
Timothy J. Ryan,94441,democrat
Ann Womer Benjamin,62188,republican
James A. Traficant Jr.,28045,independent
district_end
district:12
Patrick J. Tiberi,116982,republican
Edward Brown,64707,democrat
district_end
district:14
Dale Blanchard,51846,democrat
Sid Stone,113,independent
Steven C. LaTourette,134413,republican
district_end
district:11
Patrick A. Pappano,36146,republican
Stephanie Tubbs Jones,116590,democrat
district_end
district:6
Mike Halleck,77643,republican
Ted Strickland,113972,democrat
district_end
district:5
Roger Anderson,51872,democrat
Paul E. Gillmor,126286,republican
John Green,10096,independent
district_end
district:16
Ralph Regula,129734,republican
Jim Rice,58644,democrat
district_end
year_end
year:2001
district:5
Dannie Edmon,62138,democrat
David J. Schaffer,5881,natural law
John F. Green,5464,libertarian
Paul E. Gillmor,169857,republican
district_end
district:9
Galen Fries,4239,libertarian
Dwight E. Bryan,49446,republican
Marcy Kaptur,168547,democrat
Dennis Slotnick,3096,natural law
district_end
district:14
Walter P. Keith,3869,natural law
Rick Wood,71432,republican
William C. McDaniel, Jr.,5603,libertarian
Tom Sawyer,149184,democrat
district_end
district:8
John G. Parks,66293,democrat
David R. Shock,7254,libertarian
John A. Boehner,179756,republican
district_end
district:7
John Mitchel,13983,independent
Donald E. Minor,60755,democrat
Jack D. Null,3802,libertarian
David L. Hobson,163646,republican
district_end
district:15
Bill Buckel,64805,democrat
Deborah Pryce,156792,republican
Scott T. Smith,10700,libertarian
district_end
district:2
Charles W. Sanders,64091,democrat
Robert E. Bidwell,9266,libertarian
Rob Portman,204184,republican
district_end
district:17
Paul H. Alberty,54751,republican
Milton R. Norris,1278,libertarian
Randy D. Walter,51793,independent
James A. Traficant, Jr.,120333,democrat
Lou DÂApolito,9568,independent
Carol Ann McCoy,3154,natural law
district_end
district:6
Kenneth R. MacCutcheon,4759,libertarian
Ted Strickland,138849,democrat
Mike Azinger,96966,republican
district_end
district:12
Gregory B. Richey,2600,natural law
Pat Tiberi,139242,republican
Nick Hogan,4546,libertarian
Maryellen OÂShaughnessy,115432,democrat
Charles Ed Jordan,1566,independent
district_end
district:4
Ralph Mullinger,8278,libertarian
Michael G. Oxley,156510,republican
Daniel L. Dickman,67330,democrat
district_end
district:11
Sonja K. Glavina,3525,natural law
Joel C. Turner,4230,libertarian
Stephanie Tubbs Jones,164134,democrat
James J. Sykora,21630,republican
district_end
district:18
John R. Bargar, Sr.,4948,libertarian
Robert W. Ney,152325,republican
Marc D. Guthrie,79232,democrat
district_end
district:3
Regina Burch,36516,natural law
Tony P. Hall,177731,democrat
district_end
district:16
Richard L. Shetler,6166,libertarian
Brad Graef,3231,natural law
William Smith,62709,democrat
Ralph Regula,162294,republican
district_end
district:10
Ron Petrie,6762,libertarian
Dennis J. Kucinich,167063,democrat
Bill Smith,48930,republican
district_end
district:19
Sid Stone,10367,libertarian
Steven C. LaTourette,206639,republican
Dale Virgil Blanchard,101842,democrat
district_end
district:1
David A. Groshoff,3399,libertarian
Richard L. Stevenson,1933,natural law
John Cranley,98328,democrat
Steve Chabot,116768,republican
district_end
district:13
Rick H. Jeric,84295,republican
David C. Kluter,3108,natural law
Sherrod Brown,170058,democrat
Michael A. Chmura,5837,libertarian
district_end
year_end
year:2007
district:10
Michael D. Dovilla,69996,republican
Dennis J. Kucinich,138393,democrat
district_end
district:15
Mary Jo Kilroy,109659,democrat
Bill Buckel,194,none
Deborah Pryce,110714,republican
district_end
district:7
William R. Conner,89579,democrat
David L. Hobson,137899,republican
district_end
district:1
Steve Chabot,105680,republican
John Cranley,96584,democrat
district_end
district:12
Patrick J. Tiberi,145943,republican
Bob Shamansky,108746,democrat
district_end
district:9
Bradley S. Leavitt,55119,republican
Marcy Kaptur,153880,democrat
district_end
district:4
Richard E. Siferd,86678,democrat
Jim Jordan,129958,republican
district_end
district:2
Jean Schmidt,120112,republican
James J. Condit, Jr.,76,none
Nathan Noy,298,none
Victoria Wulsin,117595,democrat
district_end
district:11
Lindsey N. String,29125,republican
Stephanie Tubbs Jones,146799,democrat
district_end
district:17
Tim Ryan,170369,democrat
Don Manning II,41925,republican
district_end
district:14
Steven C. LaTourette,144069,republican
Lewis R. Katz,97753,democrat
Werner J. Lange,8500,none
district_end
district:16
Ralph Regula,137167,republican
Thomas Shaw,97955,democrat
district_end
district:3
Michael R. Turner,127978,republican
Richard Chema,90650,democrat
district_end
district:13
Betty Sutton,135639,democrat
Craig Foltin,85922,republican
district_end
district:18
Zack T. Space,129646,democrat
Joy Padgett,79259,republican
district_end
district:5
Paul E. Gillmor,129813,republican
Robin Weirauch,98544,democrat
district_end
district:8
Mort Meier,77640,democrat
John A. Boehner,136863,republican
district_end
district:6
Charles A. Wilson, Jr.,135628,democrat
Chuck Blasdel,82848,republican
district_end
year_end
year:2015
district:9
Richard May,51704,republican
Marcy Kaptur,108870,democrat
George A. Skalsky,29,none
Cory Hoffman,112,none
district_end
district:13
David Allen Pastorius,86,none
Tim Ryan,120230,democrat
Thomas Pekarek,55233,republican
district_end
district:14
Michael Wager,70856,democrat
David P. Joyce,135736,republican
David Macko,7988,libertarian
district_end
district:10
Michael R. Turner,130752,republican
Robert Klepinger,63249,democrat
David A. Harlow,6605,libertarian
district_end
district:8
Tom Poetter,51534,democrat
James J. Condit Jr.,10257,constitution
John A. Boehner,126539,republican
district_end
district:2
Brad R. Wenstrup,132658,republican
Marek Tyszkiewicz,68453,democrat
district_end
district:12
Bob Hart,9148,green
Patrick J. Tiberi,150573,republican
David Arthur Tibbs,61360,democrat
district_end
district:3
Ralph A. Applegate,17,none
John Adams,51475,republican
Joyce Beatty,91769,democrat
district_end
district:16
Pete Crossland,75199,democrat
James B. Renacci,132176,republican
district_end
district:15
Steve Stivers,128496,republican
Scott Wharton,66125,democrat
district_end
district:4
Jim Jordan,125907,republican
Janet Garrett,60165,democrat
district_end
district:1
Steve Chabot,124779,republican
Fred Kundrata,72604,democrat
district_end
district:6
Dennis Lambert,6065,green
Jennifer Garrison,73561,democrat
Bill Johnson,111026,republican
district_end
district:5
Robert E. Latta,134449,republican
Robert L. Fry,58507,democrat
Eric Eberly,9344,libertarian
district_end
district:11
Mark Zetzer,35461,republican
Marcia L. Fudge,137105,democrat
district_end
district:7
Bob Gibbs,143959,republican
district_end
year_end
year:2017
district:9
Marcy Kaptur,193966,democrat
George Skalsky,5,none
Donald P. Larson,88427,republican
district_end
district:14
David P. Joyce,219191,republican
Michael Wager,130907,democrat
Andrew Jarvi,171,none
district_end
district:7
Roy Rich,89638,democrat
Bob Gibbs,198221,republican
Dan Phillip,21694,no party
district_end
district:5
James Neu Jr.,100392,democrat
Robert E. Latta,244599,republican
district_end
district:1
Steve Chabot,210014,republican
Kiumars G. Kiani,16,none
Michele Young,144644,democrat
Sholom D. Keller,114,none
district_end
district:8
Warren Davidson,223833,republican
Derrick James Hendricks,13879,green
Steven Fought,87794,democrat
district_end
district:4
Jim Jordan,210227,republican
Janet Garrett,98981,democrat
district_end
district:13
Tim Ryan,208610,democrat
Richard A. Morckel,99377,republican
Calvin Hill Sr.,17,none
district_end
district:16
Keith Mundy,119830,democrat
James B. Renacci,225794,republican
district_end
district:3
Joyce Beatty,199791,democrat
John Adams,91560,republican
district_end
district:6
Michael L. Lorentz,88780,democrat
Bill Johnson,213975,republican
district_end
district:12
Patrick J. Tiberi,251266,republican
Ed Albertson,112638,democrat
Joe Manchik,13474,green
John J. Baumeister,156,none
district_end
district:10
Michael R. Turner,215724,republican
Tom McMasters,10890,no party
Robert Klepinger,109981,democrat
David A. Harlow,7,none
district_end
district:15
Scott Wharton,113960,democrat
Steve Stivers,222847,republican
district_end
district:11
Beverly A. Goldstein,59769,republican
Marcia L. Fudge,242917,democrat
district_end
district:2
Brad R. Wenstrup,221193,republican
Janet Everhard,7392,none
William R. Smith,111694,democrat
district_end
year_end
year:1999
district:17
Paul H. Alberty,57703,republican
James A. Traficant, Jr.,123718,democrat
district_end
district:9
Marcy Kaptur,130793,democrat
Edward S. Emery,30312,republican
district_end
district:3
Tony P. Hall,114198,democrat
John S. Shondel,50544,republican
district_end
district:8
John A. Boehner,127979,republican
John W. Griffin,52912,democrat
district_end
district:13
Sherrod Brown,116309,democrat
Grace L. Drake,72666,republican
district_end
district:12
John R. Kasich,124197,republican
Edward S. Brown,60694,democrat
district_end
district:18
Robert L. Burch,74571,democrat
Robert W. Ney,113119,republican
district_end
district:10
Dennis J. Kucinich,110552,democrat
Joe Slovenec,55015,republican
district_end
district:7
James A. Schrader,9146,libertarian
<write in>,6,none
David L. Hobson,120765,republican
Donald E. Minor, Jr.,49780,democrat
district_end
district:5
Susan Davenport,61926,democrat
Paul E. Gillmor,123979,republican
district_end
district:11
Jean Murrell Capers,9477,independent
Stephanie Tubbs Jones,115226,democrat
James D. Hereford,18592,republican
district_end
district:4
Michael G. Oxley,112011,republican
Paul McClain,63529,democrat
district_end
district:2
Rob Portman,154344,republican
Charles W. Sanders,49293,democrat
district_end
district:14
Thomas C. Sawyer,106046,democrat
Tom Watkins,63027,republican
district_end
district:19
Elizabeth Kelley,64090,democrat
Steven C. LaTourette,126786,republican
district_end
district:6
Nancy P. Hollister,77711,republican
Ted Strickland,102852,democrat
district_end
district:16
Peter D. Ferguson,66047,democrat
Ralph Regula,117426,republican
district_end
district:15
Adam Clay Miller,49334,democrat
Deborah Pryce,113846,republican
Kevin Nestor,9996,libertarian
district_end
district:1
Steve Chabot,92421,republican
Roxanne Qualls,82003,democrat
district_end
year_end
year:2013
district:3
Chris Long,77901,republican
Bob Fitrakis,6387,green
Joyce Beatty,201897,democrat
Richard Ehrbar,9462,libertarian
Jeff Brown,5,none
district_end
district:1
Jim Berns,9674,libertarian
Steve Chabot,201907,republican
Rich Stevenson,6645,green
Jeff Sinnard,131490,democrat
district_end
district:14
Erick Donald Robinson,1,none
Dale Virgil Blanchard,131637,democrat
David Macko,11536,libertarian
Elaine R. Mastromatteo,13038,green
Steven Winfield,5,none
David P. Joyce,183657,republican
Aaron J. Zurbrugg,20,none
district_end
district:8
James Condit, Jr.,1938,none
John A. Boehner,246378,republican
district_end
district:10
David A. Harlow,10373,libertarian
Michael R. Turner,208201,republican
Sharen Swartz Neuhardt,131097,democrat
district_end
district:5
Robert E. Latta,201514,republican
Eric Eberly,12558,libertarian
Angela Zimmann,137806,democrat
district_end
district:11
Marcia L. Fudge,258359,democrat
district_end
district:16
Betty Sutton,170600,democrat
James B. Renacci,185165,republican
district_end
district:12
Jim Reese,134605,democrat
Patrick J. Tiberi,233869,republican
district_end
district:6
Bill Johnson,164536,republican
Charlie Wilson,144444,democrat
district_end
district:13
Tim Ryan,235492,democrat
Marisha G. Agana,88120,republican
district_end
district:15
Steve Stivers,205274,republican
Pat Lang,128188,democrat
district_end
district:4
Chris Kalla,16141,libertarian
Jim Slone,114214,democrat
Jim Jordan,182643,republican
district_end
district:2
Brad Wenstrup,194296,republican
William R. Smith,137077,democrat
district_end
district:9
Marcy Kaptur,217771,democrat
Samuel J. Wurzelbacher,68668,republican
Sean P. Stipe,11725,libertarian
district_end
district:7
Bob Gibbs,178104,republican
Joyce R. Healy-Abrams,137708,democrat
district_end
year_end
year:1997
district:6
Frank A. Cremeans,111907,republican
<write in>,16,none
Ted Strickland,118003,democrat
district_end
district:19
Thomas J. Coyne Jr.,101152,democrat
Steven C. LaTourette,135012,republican
Thomas A. Martin,10655,natural law
district_end
district:15
Cliff Arnebeck Jr.,64665,democrat
Deborah Pryce,156776,republican
district_end
district:14
Terry E. Wilkinson,8976,natural law
Thomas C. Sawyer,124136,democrat
<write in>,16,none
Joyce George,95307,republican
district_end
district:9
Randy Whitman,46040,republican
Marcy Kaptur,170617,democrat
Elizabeth A. Slotnick,4677,natural law
district_end
district:17
James A. Traficant Jr.,218283,democrat
James M. Cahaney,21685,natural law
district_end
district:4
Michael McCaffery,11057,natural law
Michael G. Oxley,147608,republican
Paul Anthony McClain,69096,democrat
district_end
district:18
Robert W. Ney,117365,republican
Robert L. Burch,108332,democrat
Margaret Chitti,8146,natural law
district_end
district:3
Tony P. Hall,144583,democrat
Dorothy H. Mackey,5088,natural law
David A. Westbrock,75732,republican
<write in>,1800,none
district_end
district:10
Dennis J. Kucinich,110723,democrat
Robert B. Iverson,10415,natural law
<write in>,12,none
Martin R. Hoke,104546,republican
district_end
district:13
Sherrod Brown,148690,democrat
Kenneth C. Blair Jr.,87108,republican
David Kluter,8707,natural law
district_end
district:12
Barbara Ann Edelman,7005,natural law
John R. Kasich,151667,republican
Cynthia L. Ruccia,78762,democrat
district_end
district:11
Sonja Glavina,6665,natural law
Louis Stokes,153546,democrat
<write in>,7,none
James J. Sykora,28821,republican
district_end
district:16
Thomas E. Burkhart,64902,democrat
Ralph Regula,159314,republican
Brad Graef,7611,natural law
district_end
district:1
John G. Halley,5381,natural law
Mark P. Longabaugh,94719,democrat
Steve Chabot,118324,republican
district_end
district:2
Thomas R. Chandler,58715,democrat
Rob Portman,186853,republican
Kathleen M. McKnight,13905,natural law
district_end
district:7
David L. Hobson,158087,republican
Richard K. Blain,61419,democrat
<write in>,17,none
Dawn Marie Johnson,13478,natural law
district_end
district:5
Annie Saunders,81170,democrat
Paul E. Gilmor,145892,republican
David J. Schaffer,11461,natural law
district_end
district:8
Jeffrey D. Kitchen,61515,democrat
John A. Boehner,165815,republican
William Baker,8613,natural law
district_end
year_end
year:2011
district:11
Thomas Pekarek,28754,republican
Marcia L. Fudge,139693,democrat
district_end
district:4
Donald Charles Kissick,7708,libertarian
Doug Litt,50533,democrat
Jim Jordan,146029,republican
district_end
district:8
James J. Condit, Jr.,3701,constitution
John A. Boehner,142731,republican
David A. Harlow,5121,libertarian
Justin A. Coussoule,65883,democrat
district_end
district:5
Robert E. Latta,140703,republican
Caleb Finkenbiner,54919,democrat
Brian L. Smith,11831,libertarian
district_end
district:1
Steve Chabot,103770,republican
Rich Stevenson,2000,green
Jim Berns,3076,libertarian
Steve Driehaus,92672,democrat
district_end
district:15
David Ryon,3887,constitution
Bill Buckel,45,none
Steve Stivers,119471,republican
William J. Kammerer,6116,libertarian
Mary Jo Kilroy,91077,democrat
district_end
district:16
Jeffrey J. Blevins,14585,libertarian
Robert L. Ross,67,none
John A. Boccieri,90833,democrat
Jim Renacci,114652,republican
district_end
district:7
Steve Austria,135721,republican
Bill Conner,70400,democrat
John D. Anderson,9381,libertarian
David W. Easton,2811,constitution
district_end
district:17
Jim Graham,57352,republican
Tim Ryan,102758,democrat
James A. Traficant, Jr.,30556,independent
district_end
district:6
Martin J. Elsass,4505,libertarian
Bill Johnson,103170,republican
Charles A. Wilson,92823,democrat
Richard E. Cadle,5077,constitution
district_end
district:18
Mark Pitrone,20,none
Zachary T. Space,80756,democrat
Bob Gibbs,107426,republican
Lindsey Dean Sutton,11246,constitution
district_end
district:2
Jean Schmidt,139027,republican
Randy Lee Conover,128,none
Surya Yalamanchili,82431,democrat
Marc Johnston,16259,libertarian
district_end
district:14
John M. Jelenic,8383,libertarian
Bill O'Neill,72604,democrat
Steven C. LaTourette,149878,republican
district_end
district:12
Patrick J. Tiberi,150163,republican
Paula Brooks,110307,democrat
Travis M. Irvine,8710,libertarian
district_end
district:13
Rom Ganley,94367,republican
Betty Sutton,118806,democrat
district_end
district:9
Marcy Kaptur,121819,democrat
Rich Iott,83423,republican
district_end
district:10
Peter J. Corrigan,83809,republican
Dennis J. Kucinich,101343,democrat
Jeff Goggins,5874,libertarian
district_end
district:3
Michael R. Turner,152629,republican
Joe Roberts,71455,democrat
district_end
year_end
year:2009
district:17
Tim Ryan,218896,democrat
Duane V. Grassell,61216,republican
district_end
district:3
Michael R. Turner,200204,republican
Jane Mitakides,115976,democrat
district_end
district:9
Bradley S. Leavitt,76512,republican
Marcy Kaptur,222054,democrat
district_end
district:10
Paul Conroy,10623,libertarian
Jim Trakas,107918,republican
Dennis J. Kucinich,157268,democrat
district_end
district:15
Travis Casper,6,independent
Mark Michael Noble,14061,libertarian
Steve Stivers,137272,republican
Mary Jo Kilroy,139584,democrat
Don Elijah Eckhart,12915,independent
district_end
district:2
Victoria Wulsin,124213,democrat
James Condit Jr.,30,independent
Jean Schmidt,148671,republican
David H. Krikorian,58710,independent
district_end
district:1
Eric Wilson,85,independent
Rich Stevenson,67,independent
Steve Driehaus,155455,democrat
Steve Chabot,140683,republican
district_end
district:12
Patrick J. Tiberi,197447,republican
David Robinson,152234,democrat
Steven R. Linnabary,10707,libertarian
district_end
district:14
Bill O'Neill,125214,democrat
Steven C. LaTourette,188488,republican
David Macko,9511,libertarian
district_end
district:11
Marcia L. Fudge,212667,democrat
Thomas Pekarek,36708,republican
Eric Johnson,23,independent
Craig E. Willis,144,independent
district_end
district:8
John A. Boehner,202063,republican
Nicholas A. Von Stein,95510,democrat
district_end
district:6
Richard D. Stobbs,92968,republican
Charles A. Wilson,176330,democrat
Dennis Spisak,13812,green
district_end
district:5
George F. Mays,105840,democrat
Robert E. Latta,188905,republican
district_end
district:16
John A. Boccieri,169044,democrat
Kirk Schuring,136293,republican
district_end
district:18
Zachary T. Space,164187,democrat
Fred Dailey,110031,republican
district_end
district:13
David S. Potter,105050,republican
Betty Sutton,192593,democrat
Robert Crow,37,independent
district_end
district:7
Steve Austria,174915,republican
Sharen Swartz Neuhardt,125547,democrat
district_end
district:4
Jim Jordan,186154,republican
Mike Carroll,99499,democrat
district_end
year_end
year:2005
district:17
Frank V. Cusimano,62871,republican
Tim Ryan,212800,democrat
district_end
district:4
Ben Konop,118538,democrat
Michael G. Oxley,167807,republican
district_end
district:18
Robert W. Ney,177600,republican
Brian R. Thomas,90820,democrat
district_end
district:12
Patrick J. Tiberi,198912,republican
Edward S. Brown,122109,democrat
Chuck Spingola,25,nonpartisan
district_end
district:5
Robin Weirauch,96656,democrat
Paul E. Gillmor,196649,republican
district_end
district:14
Steven C. LaTourette,201652,republican
Capri S. Cafaro,119714,democrat
district_end
district:10
Edward Fitzpatrick Herman,96463,republican
Dennis J. Kucinich,172406,democrat
Barbara Anne Ferris,18343,nonpartisan
district_end
district:9
Larry A. Kaczala,95983,republican
Marcy Kaptur,205149,democrat
district_end
district:1
Steve Chabot,173430,republican
Greg Harris,116235,democrat
Rich Stevenson,198,nonpartisan
district_end
district:8
John A. Boehner,201675,republican
Jeff Hardenbrook,90574,democrat
district_end
district:7
Kara Anastasio,100617,democrat
David L. Hobson,186534,republican
district_end
district:6
John Stephen Luchanksy,145,nonpartisan
Ted Strickland,223842,democrat
district_end
district:2
Charles W. Sanders,89598,democrat
James Condit, Jr.,60,nonpartisan
Rob Portman,227102,republican
district_end
district:16
Ralph Regula,202544,republican
Jeff Seemann,101817,democrat
district_end
district:15
Mark P. Brown,110915,democrat
Deborah Pryce,166520,republican
district_end
district:13
Robert Lucas,97090,republican
Sherrod Brown,201004,democrat
district_end
district:11
Stephanie Tubbs Jones,222371,democrat
district_end
district:3
Jane Mitakides,119448,democrat
Michael R. Turner,197290,republican
district_end
year_end
