year:1997
district:3
Joseph M. McColgan,54681,republican
Robert A. Borski,121120,democrat
district_end
district:20
Mike McCormick,97004,republican
<write in>,4,none
Frank Mascara,113394,democrat
district_end
district:8
James C. Greenwood,133749,republican
Richard J. Piotrowski,6991,libertarian
John P. Murray,79856,democrat
<write in>,12,none
David A. Booth,5714,constitution
district_end
district:1
James D. Cella,20734,republican
Thomas M. Foglietta,145210,democrat
<write in>,1,none
district_end
district:10
Thomas J. McLaughlin,8311,reform
Joseph M. McDade,124670,republican
<write in>,23,none
Joe Cullen,75536,democrat
district_end
district:19
<write in>,109,none
William F. Goodling,130716,republican
Francis Worley,3194,francis worley congress
Scott L. Chronister,74944,democrat
district_end
district:13
Joseph M. Hoeffel,120220,democrat
Bill Ryan,525,natural law
Jon D. Fox,120304,republican
Thomas Patrick Burke,4930,libertarian
district_end
district:11
Stephen A. Urban,60339,republican
<write in>,12,none
Paul E. Kanjorski,128258,democrat
district_end
district:18
Ralph A. Emmerich,883,natural law
Michael F. Doyle,120410,democrat
Richard Edward Caligiuri,6859,independent
David B. Fawcett,86829,republican
<write in>,9,none
district_end
district:5
<write in>,73,none
John E. Peterson,116303,republican
Ruth C. Rudy,76627,democrat
district_end
district:12
John P. Murtha,136815,democrat
<write in>,23,none
Bill Choby,58643,republican
district_end
district:2
<write in>,3,none
Larry G. Murphy,23047,republican
Chaka Fattah,168887,democrat
district_end
district:9
Bud Shuster,142105,republican
Monte Kemmler,50650,democrat
<write in>,67,none
district_end
district:14
William J. Coyne,122922,democrat
Paul Scherrer,713,socialist equality
Bill Ravotti,78921,republican
<write in>,22,none
district_end
district:16
James G. Blaine,78598,democrat
<write in>,8,none
Joseph R. Pitts,124511,republican
Robert S. Yorczyk,6485,reform
district_end
district:21
<write in>,9,none
Ronald A. Dinicola,104004,democrat
Phil English,106875,republican
district_end
district:7
<write in>,16,none
John Pronchik,1688,natural law
John F. Innelli,79875,democrat
Curt Weldon,165087,republican
district_end
district:15
Paul McHale,109812,democrat
<write in>,5,none
Philip E. Faust,812,natural law
Nicholas R. Sabatine III,6931,reform
Bob Kilbanks,82803,republican
district_end
district:17
George W. Gekas,150678,republican
<write in>,27,none
Paul Kattl,57911,democrat
district_end
district:4
Paul T. Adametz,79448,republican
Ron Klink,142621,democrat
<write in>,98,none
district_end
district:6
Thomas E. List,1475,natural law
Tim Holden,115193,democrat
Christian Y. Leinbach,80061,republican
district_end
year_end
year:2011
district:12
Mark S. Critz,94056,democrat
Tim Burns,91170,republican
district_end
district:14
Melissa Haluszczak,49997,republican
Michael F. Doyle,122073,democrat
Ed Bortz,5400,green
district_end
district:5
Glenn Thompson,127427,republican
Michael Pipe,52375,democrat
Vernon L. Etzel,5710,libertarian
district_end
district:4
Keith Rothfus,116958,republican
Jason Altmire,120827,democrat
district_end
district:7
James D. Schneller,2708,american congress party
Bryan Lentz,110314,democrat
Patrick Meehan,137825,republican
district_end
district:15
Jake Towne,15248,towne for congress
Charles W. Dent,109534,republican
John B. Callahan,79766,democrat
district_end
district:16
Joseph R. Pitts,134113,republican
Lois Herr,70994,democrat
district_end
district:19
Joshua A. Monighan,10988,independent
Ryan S. Sanders,53549,democrat
Rodd Russell Platts,165219,republican
district_end
district:6
Jim Gerlach,133770,republican
Manan Trivedi,100493,democrat
district_end
district:10
Christopher P. Carney,89846,democrat
Thomas A. Marino,110599,republican
district_end
district:18
Dan Connolly,78558,democrat
Tim Murphy,161888,republican
district_end
district:3
Mike Kelly,111909,republican
Kathleen A. Dahlkemper,88924,democrat
district_end
district:17
Dave Argall,95000,republican
Tim Holden,118486,democrat
district_end
district:11
Louis J. Barletta,102179,republican
Paul E. Kanjorski,84618,democrat
district_end
district:8
Michael G. Fitzpatrick,130759,republican
Patrick J. Murphy,113547,democrat
district_end
district:13
Allyson Y. Schwartz,118710,democrat
Carson Dee Adcock,91987,republican
district_end
district:2
Rick Hellberg,21907,republican
Chaka Fattah,182800,democrat
district_end
district:9
Tom Conners,52322,democrat
Bill Shuster,141904,republican
district_end
district:1
Robert A. Brady,149944,democrat
district_end
year_end
year:2017
district:9
Art Halvorson,107985,democrat
Bill Shuster,186580,republican
district_end
district:15
Rich Daugherty,124129,democrat
Paul Rizzo,11727,libertarian
Charles W. Dent,190618,republican
district_end
district:14
Michael F. Doyle,255293,democrat
Lenny McAllister,87999,republican
district_end
district:7
Mary Ellen Balchunis,153824,democrat
Patrick Meehan,225678,republican
district_end
district:16
Christina Hartman,134586,democrat
Shawn Patrick House,10518,libertarian
Lloyd K. Smucker,168669,republican
district_end
district:6
Mike Parrish,155000,democrat
Ryan A. Costello,207469,republican
district_end
district:5
Glenn Thompson,206761,republican
Kerith Strano Taylor,101082,democrat
district_end
district:8
Steve Santarsiero,173555,democrat
Brian Fitzpatrick,207263,republican
district_end
district:11
Mike Marsicano,113800,democrat
Lou Barletta,199421,republican
district_end
district:10
Mike Molesevich,89823,democrat
Tom Marino,211282,republican
district_end
district:18
Tim Murphy,293684,republican
district_end
district:3
Mike Kelly,244893,republican
district_end
district:4
Joshua Burkholder,113372,democrat
Scott Perry,220628,republican
district_end
district:2
Dwight Evans,322514,democrat
James A. Jones,35131,republican
district_end
district:1
Robert A. Brady,245791,democrat
Deborah Williams,53219,republican
district_end
district:12
Keith J. Rothfus,221851,republican
Erin R. McClelland,137353,democrat
district_end
district:17
Matt Cartwright,157734,democrat
Matt Connolly,135430,republican
district_end
district:13
Brendan F. Boyle,239316,democrat
district_end
year_end
year:2013
district:15
Charles W. Dent,168960,republican
Rick Daugherty,128764,democrat
district_end
district:6
Manan M. Trivedi,143803,democrat
Jim Gerlach,191725,republican
district_end
district:2
James Foster,4829,independent
Robert Allen Mansfield, Jr.,33381,republican
Chaka Fattah,318176,democrat
district_end
district:4
Michael Bryant Koffenberger,6210,libertarian
Scott Perry,181603,republican
Wayne W. Wolff,11524,independent
Harry Perkinson,104643,democrat
district_end
district:17
Matthew A. Cartwright,161393,democrat
Laureen A. Cummings,106208,republican
district_end
district:12
Mark S. Critz,163589,democrat
Keith J. Rothfus,175352,republican
district_end
district:16
John A. Murphy,12250,independent
James F. Bednarski,5154,bednarski for congress
Joseph R. Pitts,156192,republican
Aryanna C. Strader,111185,democrat
district_end
district:18
Larry Maggi,122146,democrat
Tim Murphy,216727,republican
district_end
district:7
George Badey,143509,democrat
Patrick Meehan,209942,republican
district_end
district:9
Bill Shuster,169177,republican
Karen Ramsburg,105128,democrat
district_end
district:1
John Featherman,41708,republican
Robert A. Brady,235394,democrat
district_end
district:3
Missa Eaton,123933,democrat
Mike Kelly,165826,republican
Steven Porter,12755,independent
district_end
district:11
Lou Barletta,166967,republican
Gene Stilp,118231,democrat
district_end
district:8
Kathy Boockvar,152859,democrat
Michael G. Fitzpatrick,199379,republican
district_end
district:14
Hans Lessmann,75702,republican
Michael F. Doyle,251932,democrat
district_end
district:5
Charles Dumas,104725,democrat
Glenn Thompson,177740,republican
district_end
district:10
Philip Scollo,94227,democrat
Tom Marino,179563,republican
district_end
district:13
Allyson Y. Schwartz,209901,democrat
Joseph James Rooney,93918,republican
district_end
year_end
year:2001
district:12
James N. OÂNeil,3324,reform
Bill Choby,56575,republican
John P. Murtha,145538,democrat
district_end
district:15
Patrick J. Toomey,118307,republican
Ed OÂBrien,103864,democrat
district_end
district:4
Terry E. Van Horne,100995,democrat
Melissa Hart,145390,republican
district_end
district:1
Robert A. Brady,149621,democrat
Steven N. Kush,19920,republican
district_end
district:16
Bob Yorczyk,80177,democrat
Joseph R. Pitts,162403,republican
district_end
district:21
Phil English,135164,republican
Marc A. Flitter,87018,democrat
district_end
district:8
James C. Greenwood,154090,republican
Ronald L. Strouse,100617,democrat
Philip C. Holmen,5394,reform
district_end
district:9
Bud Shuster,184401,republican
district_end
district:19
Todd Platts,168722,republican
Michael L. Paoletta,2234,constitution
Jeff Sanders,61538,democrat
district_end
district:5
John E. Peterson,147570,republican
William M. Belitskus,13857,green
Thomas A. Martin,11020,libertarian
district_end
district:20
Frank Mascara,145131,democrat
Ronald J. Davis,80312,republican
district_end
district:18
Craig C. Stephens,68798,republican
Michael F. Doyle,156131,democrat
district_end
district:10
Don Sherwood,124830,republican
Pat Casey,112580,democrat
district_end
district:7
Peter A. Lennon,93687,democrat
Curt Weldon,172569,republican
district_end
district:13
Joseph M. Hoeffel,146026,democrat
Stewart J. Greenleaf,126501,republican
Ken Cavanaugh,4224,libertarian
district_end
district:2
Chaka Fattah,180021,democrat
Kenneth V. Krawchuk,3673,libertarian
district_end
district:14
William J. Coyne,147533,democrat
district_end
district:6
Thomas G. Kopel,71227,republican
Tim Holden,140084,democrat
district_end
district:11
Stephen A. Urban,66699,republican
Paul E. Kanjorski,131948,democrat
district_end
district:17
Leslye Hess Herrmann,66190,democrat
George W. Gekas,166236,republican
district_end
district:3
Charles F. Dougherty,59343,republican
Robert A. Borski,130528,democrat
district_end
year_end
year:1999
district:21
Phil English,94518,republican
<write in>,6,none
Larry Klemens,54591,democrat
district_end
district:1
Nancy Cole,964,workers campaign
William M. Harrison,15898,republican
Robert A. Brady,77788,democrat
John Featherman,1198,libertarian
district_end
district:4
<write in>,17,none
Ron Klink,103183,democrat
Mike Turzai,58485,republican
district_end
district:16
<write in>,14,none
Robert S. Yorczyk,40092,democrat
Joseph R. Pitts,95979,republican
district_end
district:19
<write in>,87,none
Linda G. Ropp,40674,democrat
William F. Goodling,96284,republican
Gary M. Shoemaker,5444,libertarian
district_end
district:5
<write in>,87,none
John E. Peterson,99502,republican
William M. Belitskus,17734,green
district_end
district:14
Dorothy L. Kolis,1625,socialist workers
Bill Ravotti,52745,republican
<write in>,11,none
William J. Coyne,83355,democrat
district_end
district:11
Paul E. Kanjorski,88933,democrat
Stephen A. Urban,44123,republican
<write in>,9,none
district_end
district:3
Charles F. Dougherty,45390,republican
Robert A. Borski,66270,democrat
district_end
district:8
<write in>,15,none
Carolyn Boyce,1022,natural law
Scott Wolfertz,3917,constitutional
Bill Tuthill,48320,democrat
James C. Greenwood,93697,republican
James R. Blair,1229,reform
district_end
district:12
John P. Murtha,100528,democrat
<write in>,13,none
Timothy E. Holloway,46239,republican
district_end
district:20
<write in>,190,none
Frank Mascara,97885,democrat
district_end
district:15
Pat Toomey,81755,republican
Roy C. Afflerbach,66930,democrat
<write in>,21,none
district_end
district:10
Patrick Casey,83760,democrat
Thomas J. McLaughlin,4998,reform
Don Sherwood,84275,republican
<write in>,23,none
district_end
district:18
Dick Walker,46945,republican
Michael F. Doyle,98363,democrat
<write in>,29,none
district_end
district:2
Chaka Fattah,102763,democrat
Anne Marie Mulligan,16001,republican
district_end
district:17
George W. Gekas,114931,republican
<write in>,176,none
district_end
district:7
Curt Weldon,119491,republican
Martin J. D'Urso,46920,democrat
district_end
district:13
Jon D. Fox,85915,republican
Joseph M. Hoeffel,95105,democrat
Thomas Patrick Burke,3470,libertarian
district_end
district:6
John Meckley,54579,republican
Tim Holden,85374,democrat
district_end
district:9
Bud Shuster,125409,republican
<write in>,618,none
district_end
year_end
year:2009
district:8
Patrick J. Murphy,197869,democrat
Tom Lingenfelter,5543,independent
Tom Manion,145103,republican
district_end
district:15
Sam Bennett,128333,democrat
Charles W. Dent,181433,republican
district_end
district:5
Glenn W. Thompson,155513,republican
James Fryman,6155,libertarian
Mark B. McCracken,112509,democrat
district_end
district:13
John P. McDermott,8374,constitution
Allyson Y. Schwartz,196868,democrat
Marina Kats,108271,republican
district_end
district:11
Paul E. Kanjorski,146379,democrat
Lou Barletta,137151,republican
district_end
district:2
Chaka Fattah,276870,democrat
Adam A. Lang,34466,republican
district_end
district:6
Jim Gerlach,179423,republican
Bob Roggio,164952,democrat
district_end
district:16
Joseph R. Pitts,170329,republican
Daniel Frank,2877,constitution
John A. Murphy,11768,independent
Bruce A. Slater,120193,democrat
district_end
district:14
Michael F. Doyle,242326,democrat
Titus North,23214,green
district_end
district:19
Philip J. Avillo Jr.,109533,democrat
Todd Russell Platts,218862,republican
district_end
district:18
Steve O'Donnell,119661,democrat
Tim Murphy,213349,republican
district_end
district:12
John P. Murtha,155268,democrat
William Russell,113120,republican
district_end
district:17
Tim Holden,192699,democrat
Toni Gilhooley,109909,republican
district_end
district:7
Joe Sestak,209955,democrat
W. Craig Williams,142362,republican
district_end
district:4
Melissa Hart,147411,republican
Jason Altmire,186536,democrat
district_end
district:10
Christopher P. Carney,160837,democrat
Chris Hackett,124681,republican
district_end
district:1
Mike Muhammad,24714,republican
Robert A. Brady,242799,democrat
district_end
district:3
Kathy Dahlkemper,146846,democrat
Phil English,139707,republican
district_end
district:9
Bill Shuster,174951,republican
Tony Barr,98735,democrat
district_end
year_end
year:2007
district:14
<write in>,606,none
Michael F. Doyle,161075,democrat
Titus North,17720,green
district_end
district:9
Tony Barr,79610,democrat
<write in>,141,none
Bill Shuster,121069,republican
district_end
district:19
Todd Russell Platts,142512,republican
<write in>,121,none
Philip J. Avillo, Jr.,74625,democrat
Derf W. Maitland,5640,green
district_end
district:12
Diana Irey,79612,republican
<write in>,79,none
John P. Murtha,123472,democrat
district_end
district:7
Curt Weldon,114426,republican
<write in>,110,none
Joe Sestak,147898,democrat
district_end
district:16
<write in>,55,none
Joseph R. Pitts,115741,republican
Lois K. Herr,80915,democrat
John A. Murphy,7958,independent
district_end
district:10
Don Sherwood,97862,republican
Christopher Carney,110115,democrat
<write in>,196,none
district_end
district:15
Greta Browne,5802,green
Charles W. Dent,106153,republican
<write in>,32,none
Charles Dertinger,86186,democrat
district_end
district:5
Donald L. Hilliard,76456,democrat
<write in>,145,none
John E. Peterson,115126,republican
district_end
district:6
Jim Gerlach,121047,republican
Lois Murphy,117892,democrat
district_end
district:8
<write in>,23,none
Michael G. Fitzpatrick,124138,republican
Patrick J. Murphy,125656,democrat
district_end
district:4
Melissa A. Hart,122049,republican
<write in>,188,none
Jason Altmire,131847,democrat
district_end
district:1
Robert A. Brady,137987,democrat
<write in>,12,none
district_end
district:11
Joseph F. Leonardi,51033,republican
<write in>,40,none
Paul E. Kanjorski,134340,democrat
district_end
district:17
Tim Holden,137253,democrat
Matthew A. Wertz,75455,republican
<write in>,69,none
district_end
district:2
Chaka Fattah,165867,democrat
Michael Gessner,17291,republican
David G. Baker,4125,green
district_end
district:3
Steven Porter,85110,democrat
Phil English,108525,republican
<write in>,177,none
Timothy J. Hagberg,8706,constitution
district_end
district:13
Allyson Y. Schwartz,147368,democrat
Raj Peter Bhakta,75492,republican
district_end
district:18
Chad Kluko,105419,democrat
<write in>,189,none
Tim Murphy,144632,republican
district_end
year_end
year:2003
district:13
John P. McDermott,3627,constitution
Joseph M. Hoeffel,107945,democrat
Melissa Brown,100295,republican
district_end
district:6
Jim Gerlach,103648,republican
<write in>,15,none
Dan Wofford,98128,democrat
district_end
district:12
<write in>,9,none
John P. Murtha,124201,democrat
Bill Choby,44818,republican
district_end
district:15
Edward J. O'Brien,73212,democrat
<write in>,8,none
Patrick J. Toomey,98493,republican
district_end
district:5
John E. Peterson,124942,republican
<write in>,191,none
Thomas A. Martin,18078,libertarian
district_end
district:4
Melissa A. Hart,130534,republican
<write in>,10,none
Steven Drobac Jr.,71674,democrat
district_end
district:14
Michael F. Doyle,123323,democrat
<write in>,89,none
district_end
district:3
<write in>,12,none
Phil English,116763,republican
Anndrea M. Benson,33554,green
district_end
district:1
Mike Ewall,1570,green
Marie G. Delany,17444,republican
Robert A. Brady,121076,democrat
district_end
district:7
Curt Weldon,146296,republican
Peter A. Lennon,75055,democrat
district_end
district:11
<write in>,10,none
Louis J. Barletta,71543,republican
Thomas J. McLaughlin,3304,reform
Paul E. Kanjorski,93758,democrat
district_end
district:18
Tim Murphy,119885,republican
<write in>,13,none
Jack Machek,79451,democrat
district_end
district:8
Timothy T. Reece,76178,democrat
James C. Greenwood,127475,republican
<write in>,34,none
district_end
district:19
Ben Price,7900,green
<write in>,140,none
Michael Mickey Paoletta,6008,libertarian
Todd Russell Platts,143097,republican
district_end
district:2
Thomas G. Dougherty,20988,republican
Chaka Fattah,150623,democrat
district_end
district:9
<write in>,107,none
John R. Henry,50558,democrat
Bill Shuster,124184,republican
district_end
district:17
<write in>,6,none
Tim Holden,103483,democrat
George W. Gekas,97802,republican
district_end
district:16
Kenneth Brenneman,6766,constitution
Will Todd,8720,green
<write in>,65,none
Joseph R. Pitts,119046,republican
district_end
district:10
<write in>,529,none
Kurt J. Shotko,11613,green
Don Sherwood,152017,republican/democrat
district_end
year_end
year:2015
district:18
Tim Murphy,166076,republican
district_end
district:8
Michael G. Fitzpatrick,137731,republican
Kevin Strouse,84767,democrat
district_end
district:16
Joseph R. Pitts,101722,republican
Tom Houghton,74513,democrat
district_end
district:5
Kerith Strano Taylor,65839,democrat
Glenn Thompson,115018,republican
district_end
district:15
Charles W. Dent,128285,republican
district_end
district:4
Scott Perry,147090,republican
Linda Deliah Thompson,50250,democrat
district_end
district:3
Dan Lavallee,73931,democrat
Mike Kelly,113859,republican
district_end
district:13
Brendan F. Boyle,123601,democrat
Carson Dee Adcock,60549,republican
district_end
district:2
Armond James,25397,republican
Chaka Fattah,181141,democrat
district_end
district:11
Andy Ostrowski,62228,democrat
Lou Barletta,122464,republican
district_end
district:14
Michael F. Doyle,148351,democrat
district_end
district:7
Patrick Meehan,145869,republican
Mary Ellen Balchunis,89256,democrat
district_end
district:1
Megan Rath,27193,republican
Robert A. Brady,131248,democrat
district_end
district:17
David J. Moylan,71371,republican
Matt Cartwright,93680,democrat
district_end
district:10
Tom Marino,112851,republican
Nicholas Troiano,22734,independent
Scott F. Brion,44737,democrat
district_end
district:6
Ryan Costello,119643,republican
Manan Trivedi,92901,democrat
district_end
district:12
Keith J. Rothfus,127993,republican
Erin McClelland,87928,democrat
district_end
district:9
Bill Shuster,110094,republican
Alanna Hartzok,63223,democrat
district_end
year_end
year:2005
district:18
Tim Murphy,197894,republican
Mark G. Boles,117420,democrat
district_end
district:13
John P. McDermott,5291,constitution
Allyson Schwartz,171763,democrat
Melissa Brown,127205,republican
Chuck Moulton,3865,libertarian
district_end
district:8
Arthur L. Farnsworth,3710,libertarian
Michael G. Fitzpatrick,183229,republican
Virginia Waters Schrader,143427,democrat
Eric h G. Lukas,898,constitution
district_end
district:17
Tim Holden,172412,democrat
Russ Diamond,5782,libertarian
Scott Paterno,113592,republican
district_end
district:11
Paul E. Kanjorski,171147,democrat
Kenneth C. Brenneman,10105,constitution
district_end
district:14
Michael F. Doyle,220139,democrat
district_end
district:4
Stevan Drobac, Jr.,116303,democrat
Melissa A. Hart,204329,republican
Steven B. Larchuk,3285,healthcare
district_end
district:16
William R. Hagen,3269,green
Lois K. Herr,98410,democrat
Joseph R. Pitts,183620,republican
district_end
district:19
Michael Mickey Paoletta,8456,libertarian
Todd Russell Platts,224274,republican
Lester B. Searer,3474,constitution
Charles J. Steel,8890,green
district_end
district:7
David Jahn,3039,libertarian
Paul Scoles,134932,democrat
Curt Weldon,196556,republican
district_end
district:15
Joe Driscoll,114646,democrat
Charles W. Dent,170634,republican
Greta Browne,2194,green
Richard J. Piotrowski,3660,libertarian
district_end
district:5
Thomas A. Martin,26239,libertarian
John E. Peterson,192852,republican
district_end
district:12
John P. Murtha,204504,democrat
district_end
district:1
Deborah L. Williams,33266,republican
Christopher Randolph,857,randolph for congress
Robert A. Brady,214462,democrat
district_end
district:9
Bill Shuster,184320,republican
Paul I. Politis,80787,democrat
district_end
district:10
Veronica A. Hannevig,14805,constitution
Don Sherwood,191967,republican
district_end
district:6
Lois Murphy,153977,democrat
Jim Gerlach,160348,republican
district_end
district:3
Steven Porter,110684,democrat
Phil English,166580,republican
district_end
district:2
Chaka Fattah,253226,democrat
Stewart Bolno,34411,republican
district_end
year_end
