year:2015
district:6
Amos Scott Powers,37232,democrat
Diane Black,115231,republican
Mike Winton,9634,independent
district_end
district:9
Steve Cohen,87376,democrat
Paul Cook,752,independent
Herbert Bass,483,independent
Charlotte Bergmann,27173,republican
Floyd Wayne Alberson,766,independent
district_end
district:5
Jim Cooper,96148,democrat
Bob Ries,55078,republican
Paul Deakin,3050,independent
district_end
district:7
Daniel Cramer,42280,democrat
Leonard D. Ladner,5093,independent
Marsha Blackburn,110534,republican
district_end
district:1
Michael D. Salyer,4148,independent
Robert D. Franklin,9906,independent
Robert N. Smith,9869,green
David P. Roe,115533,republican
Scott Kudialis,14,independent
district_end
district:8
Wes Bradley,42433,democrat
Dana Matheny,4,independent
Mark Rawles,4451,constitution
Stephen Lee Fincher,122255,republican
James Hart,3452,independent
district_end
district:4
Scott Des Jarlais,84815,republican
Robert Rankin Doggart,9246,independent
Lendra Sherrell,51357,democrat
district_end
district:3
Cassandra J. Mitchell,4770,independent
Mary M. Headrick,53983,democrat
Charles J. "Chuck" Fleischmann,97344,republican
district_end
district:2
Bob Scott,37612,democrat
Norris Dryer,4033,green
John J. Duncan Jr.,120883,republican
Casey Adam Gouge,4223,independent
district_end
year_end
year:2009
district:4
Kevin Ragsdale,3713,independent
Monty J. Lankford,94447,republican
James Anthony Gray,4869,independent
Lincoln Davis,146776,democrat
district_end
district:5
John P. Miglietta,3196,independent
Jon Jackson,5464,independent
Jim Cooper,181467,democrat
Thomas F. Kovach,4,none
Gerard Donovan,85471,republican
district_end
district:3
Jean Howard-Hill,4848,independent
Zach Wamp,184964,republican
Doug Vandagriff,73059,democrat
June Griffin,7,none
Ed Choate,3750,independent
district_end
district:6
Bart Gordon,194264,democrat
Chris Baker,66764,independent
district_end
district:2
John J. Duncan Jr.,227120,republican
Bob Scott,63639,democrat
district_end
district:8
John S. Tanner,180465,democrat
James Hart,54,none
district_end
district:7
Randy G. Morris,99549,democrat
Marsha Blackburn,217332,republican
district_end
district:9
Dewey Clark,10047,independent
Mary "Taylor Shelby" Wright,6434,independent
Jake Ford,11003,independent
Steve Cohen,198798,democrat
district_end
district:1
Thomas "T. K." Owens,1981,independent
Joel Goodman,3988,independent
Rob Russell,57525,democrat
James W. Reeves,2544,independent
Phil Roe,168343,republican
district_end
year_end
year:2013
district:5
Brad Staats,86240,republican
Sean Puckett,12,none
John Miglietta,5222,green
Jim Cooper,171621,democrat
district_end
district:2
Brandon Stewart,2974,independent
Norris Dryer,5733,green
John J. Duncan, Jr.,196894,republican
Troy Christopher Goodale,54522,democrat
Greg Samples,4382,independent
district_end
district:1
Alan Woodruff,47663,democrat
Michael D. Salyer,2048,independent
Robert N. Smith,2872,green
Karen Sherry Brackett,4837,independent
David P. Roe,182252,republican
district_end
district:7
Credo Amouzouvik,61679,democrat
Marsha Blackburn,182730,republican
Jack Arnold,4256,independent
Leonard D. ??Lenny?? Ladner,1261,independent
Wm. Ryan Akin,2740,independent
Howard Switzer,4640,green
district_end
district:3
Mary M. Headrick,91094,democrat
Matthew Deniston,7905,independent
Richard Hall,18,none
Jean ??Lady J?? Howard-Hill,62,none
Charles J. ??Chuck?? Fleischmann,157830,republican
district_end
district:4
Scott DesJarlais,128568,republican
Eric Stewart,102022,democrat
district_end
district:6
Diane Black,184383,republican
Michael H. Thompson,4,none
Rachel Robinson,455,none
Scott Beasley,34766,independent
Pat Riley,21633,green
district_end
district:8
Stephen Lee Fincher,190923,republican
Timothy D. Dixon,79490,democrat
Mark J. Rawles,2870,independent
James Hart,6139,independent
district_end
district:9
Brian L. Saulsberry,1448,independent
George S. Flinn, Jr.,59742,republican
Kimberlee E. Smith,2,none
Herbert A. Bass,1,none
Steve Cohen,188422,democrat
Gregory M. Joiner,1372,independent
district_end
year_end
year:1997
district:2
<write in>,6,none
Chris G. Dimit,1306,independent
Stephen Smith,61020,democrat
John J. Duncan Jr.,150953,republican
George Njezic,289,independent
district_end
district:3
Charles N. "Chuck" Jolly,85714,democrat
<write in>,4,none
William A. Cole,1002,independent
Richard M. "Dick" Sims,294,independent
Thomas Ed Morrell,304,independent
Zach Wamp,113408,republican
Walt "Combat" Ward,718,independent
district_end
district:9
Johnny E. Kelly,156,independent
Bill Taylor,179,independent
<write in>,10,none
Greg Voehringer,327,independent
Mary D. Taylor,498,independent
Don Fox,146,independent
Silky Sullivan,957,independent
Harold E. Ford Jr.,116345,democrat
Tom Jeannette,222,independent
Del Gill,199,independent
Rod DeBerry,70951,republican
Anthony Burton,424,independent
district_end
district:6
<write in>,1,none
Steve Gill,94599,republican
Bart Gordon,123846,democrat
Jim Coffer,9125,independent
district_end
district:7
Don Trotter,64512,democrat
<write in>,10,none
Ed Bryant,126737,republican
Steven E. Romer,2483,independent
district_end
district:4
<write in>,5,none
Preston T. Spaulding,561,independent
Van Hilleary,103091,republican
J. Patrick Lyons,1075,independent
Mark Stewart,73331,democrat
district_end
district:5
Bob Clement,140264,democrat
Steven L. Edmondson,46201,republican
Mike Childers,7318,independent
district_end
district:1
Mike Fugate,440,independent
Bill Bull Durham,885,independent
James B. Taylor,1089,independent
<write in>,26,none
William L. Jenkins,117676,republican
Dave Davis,1947,independent
John Curtis,621,independent
Paul Schmidt,367,independent
Kay C. Smith,58657,democrat
district_end
district:8
Tom Watson,55024,republican
<write in>,377,none
John S. Tanner,123681,democrat
Donna Malone,4816,independent
district_end
year_end
year:1999
district:1
<write in>,75,none
Kay C. White,30710,democrat
William L. Jenkins,68904,republican
district_end
district:3
<write in>,74,none
Zach Wamp,75100,republican
James M. Lewis, Jr.,37144,democrat
Richard M. (Dick) Sims,1468,independent
district_end
district:6
Bart Gordon,75055,democrat
<write in>,104,none
Walt Masey,62277,republican
district_end
district:2
John J. Duncan,90860,republican
Robert O. Watson,4372,independent
George Njezic,2920,independent
<write in>,18,none
Greg Samples,4332,independent
district_end
district:7
<write in>,477,none
Ed Bryant,91503,republican
district_end
district:8
<write in>,22,none
John S. Tanner,76803,democrat
district_end
district:9
Harold E. Ford, Jr.,75428,democrat
Claude Burdikoff,18078,republican
Greg Voehringer,567,independent
Gwendolyn L. Moore,932,independent
<write in>,2,none
Johnny Kelly,775,independent
district_end
district:5
Bob Clement,74611,democrat
Gary I. Worden,4345,independent
AL Borgman,4983,independent
William M. Lancaster,6162,independent
<write in>,1,none
district_end
district:4
<write in>,23,none
Jerry W. Cooper,42627,democrat
Van Hilleary,62829,republican
district_end
year_end
year:2011
district:5
Jackie Miller,444,independent
James G. Whitfield II,333,independent
John "Big John" Smith,533,independent
Clark Taylor,156,independent
Jim Cooper,99162,democrat
David Hall,74204,republican
Joe D. Moore,159,independent
Bill Crook,391,independent
John P. Miglietta,396,independent
Stephen W. Collings,584,independent
district_end
district:6
Brandon E. Gore,1103,independent
Diane Black,128517,republican
David Purcell,1296,independent
Stephen R. Sprague,596,independent
Tommy N. Hay,1270,independent
Jim Boyd,2157,independent
Brett Carter,56145,democrat
district_end
district:7
Marsha Blackburn,158916,republican
J. W. "Bill" Stone,6320,independent
Greg Rabidoux,54347,democrat
district_end
district:2
Joseph R. Leinweber,2497,independent
Dave Hancock,25400,democrat
H. James Headings,509,independent
D. H. "Andy" Andrew,1993,independent
Greg Samples,1185,independent
John J. Duncan, Jr.,141796,republican
district_end
district:3
Robert Humphries,380,independent
Mark DeVol,5773,independent
Gregory C. Goodwin,380,independent
Mo Kiah,216,independent
Savas T. Kyriakidis,17077,independent
Don Barkman,811,independent
John Wolfe,45387,democrat
Chuck Fleischmann,92032,republican
district_end
district:9
Charlotte Bergmann,33879,republican
Steve Cohen,99827,democrat
Sandra Sullivan,673,independent
Perry Steele,528,independent
district_end
district:8
Donn Janes,2440,independent
Stephen Lee Fincher,98759,republican
Mark J. Rawles,1237,independent
Roy Herron,64960,democrat
James Hart,9,none
district_end
district:1
Kermit E. Steck,3110,independent
David P. Roe,123006,republican
Michael Edward Clark,26045,democrat
district_end
district:4
Paul H. Curtis,3178,independent
Gerald York,2159,independent
Scott DesJarlais,103969,republican
Lincoln Davis,70254,democrat
Richard S. Johnson,917,independent
James Gray,1714,independent
district_end
year_end
year:2007
district:7
Bill Morrison,73369,democrat
James B. ÂÂMickeyÂÂ White,898,independent
John L. Rimer,710,independent
William J. Smith,848,independent
Gayl G. Pratt,663,independent
Kathleen A. Culver,1806,independent
Marsha Blackburn,152288,republican
district_end
district:2
John Greene,45025,democrat
John J. Duncan, Jr.,157095,republican
district_end
district:4
Lincoln Davis,123666,democrat
Kenneth Martin,62449,republican
district_end
district:6
Norman R. Saliba,884,independent
Bart Gordon,129069,democrat
David R. Davis,60392,republican
Robert L. Garrison,2035,independent
district_end
district:8
James Hart,6,independent
John S. Tanner,129610,democrat
John Farmer,47492,republican
district_end
district:3
Brent Benedict,68324,democrat
Zach Wamp,130791,republican
district_end
district:9
Mark White,31002,republican
Steve Cohen,103341,democrat
Jake Ford,38243,independent
district_end
district:1
James W. Reeves,1003,independent
Mahmood (Michael) Sabri,411,independent
Rick Trent,65538,democrat
David Davis,108336,republican
Robert N. Smith,1024,independent
Michael Peavler,966,independent
district_end
district:5
Jim Cooper,122919,democrat
Thomas F. Kovach,49702,republican
Scott Knapp,1755,independent
Ginny Welsch,3766,independent
district_end
year_end
year:2005
district:2
Charles E. Howard,4978,independent
John J. Duncan,215795,republican
John Greene,52155,democrat
district_end
district:1
William L. Jenkins,172543,republican
Graham Leonard,56361,democrat
Ralph J. Ball,3061,independent
Michael Peavler,1595,independent
district_end
district:9
Harold E. Ford, Jr.,190648,democrat
Ruben E. Fort,41578,republican
Jim Maynard,166,none
district_end
district:8
Dennis Bertrand,91,none
John S. Tanner,173623,democrat
James L. Hart,59853,republican
district_end
district:7
Marsha Blackburn,232404,republican
district_end
district:4
Janice Bowling,109993,republican
Ken Martin,4194,independent
Lincoln Davis,138459,democrat
district_end
district:3
John Wolfe,84295,democrat
Jean Howard-Hill,1473,independent
Zach Wamp,166154,republican
June Griffin,3018,independent
Doug Vandagriff,1696,independent
district_end
district:5
Thomas F. Kovach,15,none
Scott Knapp,74978,republican
Jim Cooper,168970,democrat
district_end
district:6
J. Patrick Lyons,3869,independent
Norman R. Saliba,1802,independent
Bart Gordon,167448,democrat
Nick Demas,87523,republican
district_end
year_end
year:2001
district:6
Bart Gordon,168861,democrat
<write in>,1184,none
David Charles,97169,republican
Jim Coffer,4685,libertarian
district_end
district:2
John J. Duncan, Jr.,187154,republican
Kevin J. Rowland,22304,libertarian
<write in>,27,none
district_end
district:7
<write in>,65,none
Richard P. Sims,71587,democrat
Ed Bryant,171056,republican
Denis Solee,2941,libertarian
district_end
district:4
J. Patrick Lyons,2418,independent
<write in>,5,none
Van Hilleary,133622,republican
David H. Dunaway,67165,democrat
district_end
district:8
John S. Tanner,143127,democrat
Billy Yancy,54929,republican
<write in>,24,none
district_end
district:3
<write in>,80,none
Trudy Austin,3235,libertarian
Zach Wamp,139840,republican
William L. Callaway,75785,democrat
district_end
district:5
Bob Clement,149277,democrat
David Carew,6268,libertarian
<write in>,2,none
Stan Scott,50386,republican
district_end
district:1
<write in>,20,none
William L. Jenkins,157828,republican
district_end
district:9
Harold E. Ford, Jr.,143298,democrat
<write in>,36,none
district_end
year_end
year:2017
district:8
James Hart,4057,independent
Adrian M. Montague,2497,independent
Mark J. Rawles,2445,independent
Karen Free Spirit Talley-Lane,1981,independent
Shelia L. Godwin,6442,independent
David Kustoff,194386,republican
Rickey Hobson,70925,democrat
district_end
district:2
Stuart Starr,68401,democrat
John J. Duncan JR.,212455,republican
district_end
district:1
Robert D. Franklin,15702,independent
Paul Krane,6,none
Alan Bohms,39024,democrat
David P. Roe,198293,republican
district_end
district:3
Cassandra Mitchell,5075,independent
Topher Kersting,2493,independent
Rick Tyler,5098,independent
Melody Shekari,76727,democrat
Charles J. "Chuck" Fleischmann,176613,republican
district_end
district:9
Paul Cook,5203,independent
Wayne Alberson,41123,republican
Steve Cohen,171631,democrat
district_end
district:5
Stacy Ries Snyder,102433,republican
Jim Cooper,171111,democrat
district_end
district:6
David Ross,20261,independent
David W. Kent,61995,democrat
Diane Black,202234,republican
district_end
district:7
Marsha Blackburn,200407,republican
Tharon Chandler,65226,democrat
Leonard D. Ladner,11880,independent
district_end
district:4
Scott DesJarlais,165796,republican
Steven Reynolds,89141,democrat
district_end
year_end
year:2003
district:8
<write in>,18,none
Mat McClain,45853,republican
James L. Hart,4288,independent
John S. Tanner,117811,democrat
district_end
district:4
William Tharon Chandler,1073,independent
Ed Wellmann,399,independent
Janice Bowling,85680,republican
<write in>,50,none
Bert Mason,504,independent
Lincoln Davis,95989,democrat
John Ray,605,independent
district_end
district:5
Jesse Turner,877,independent
Robert Duvall,56825,republican
Jonathan D. Farley,1205,independent
John Jay Hooker,3063,independent
Jim Cooper,108903,democrat
<write in>,13,none
district_end
district:7
Tim Barron,51790,democrat
Rick Patterson,5423,independent
<write in>,31,none
Marsha Blackburn,138314,republican
district_end
district:1
William L. Jenkins,127300,republican
<write in>,1586,none
district_end
district:6
Bart Gordon,117119,democrat
Robert L. Garrison,57397,republican
<write in>,47,none
J. Patrick Lyons,3065,independent
district_end
district:9
Harold E. Ford Jr.,120904,democrat
<write in>,148,none
Tony Rush,23208,independent
district_end
district:3
John Wolfe,58824,democrat
Timothy A. Sevier,947,independent
Zach Wamp,112254,republican
William C. Bolen,1743,independent
<write in>,153,none
district_end
district:2
John J. Duncan Jr.,146887,republican
Joshua Williamson,1110,independent
John Greene,37035,democrat
<write in>,9,none
George Njezic,940,independent
district_end
year_end
