year:2005
district:3
Robert C. Scott,159373,democrat
Winsome E. Sears,70194,republican
<write in>,325,none
district_end
district:10
Frank R. Wolf,205982,republican
<write in>,375,none
James R. Socas,116654,democrat
district_end
district:7
W. Brad Blanton,74325,independent
Eric Cantor,230765,republican
<write in>,568,none
district_end
district:11
<write in>,291,none
Joesph P. Oddo,4338,independent
Tom Davis,186299,republican
Ken Longmyer,118305,democrat
district_end
district:9
Kevin R. Triplett,98499,republican
Seth A. Davis,4341,independent
Rick Boucher,150039,democrat
<write in>,68,none
district_end
district:8
Lisa Marie Cheney,106231,republican
James P. Moran,171986,democrat
James T. Hurysz,9004,independent
<write in>,698,none
district_end
district:4
<write in>,170,none
Jonathan R. Menefee,100413,democrat
J. Randy Forbes,182444,republican
district_end
district:2
<write in>,254,none
David B. Ashe,108180,democrat
Thelma D. Drake,132946,republican
district_end
district:1
Jo Ann Davis,225071,republican
<write in>,4029,none
William A. Lee,57434,independent
district_end
district:5
Virgil H. Goode, Jr.,172431,republican
<write in>,90,none
Al C. Weed II,98237,democrat
district_end
district:6
<write in>,7088,none
Bob Goodlatte,206560,republican
district_end
year_end
year:1997
district:10
Gary A. Reams,6500,independent
Robert L. "Bob" Weinberg,59145,democrat
Frank R. Wolf,169266,republican
<write in>,102,none
district_end
district:5
George C. Landrith III,70869,republican
<write in>,104,none
George R. "Tex" Wood,6627,reform
Virgil H. Goode Jr.,120323,democrat
district_end
district:4
Anthony J. "Tony" Zevgolis,43516,republican
<write in>,50,none
Norman Sisisky,160100,democrat
district_end
district:6
<write in>,71,none
Jeffrey W. Grey,61485,democrat
Bob Goodlatte,133576,republican
Jay P. Rutledge,4229,independent
district_end
district:2
John F. Tate,57586,republican
<write in>,195,none
Owen B. Pickett,106215,democrat
district_end
district:3
Robert C. Scott,118603,democrat
<write in>,34,none
Elsie Goodwyn Holland,25781,republican
district_end
district:9
Rick Boucher,122908,democrat
Thomas I. "Tom" Roberts,8080,reform
<write in>,34,none
Patrick C. Muldoon,58055,republican
district_end
district:7
Roderic H. Slayton,51206,democrat
Bradley E. Evans,11527,independent
<write in>,128,none
Tom Bliley,189644,republican
district_end
district:8
R. Ward Edmonds,6243,reform
<write in>,303,none
James P. Moran,152334,democrat
John E. Otey,64562,republican
Charles Stenard Severance,740,independent
Sarina J. Grosswald,5239,independent
district_end
district:11
C. W. "Levi" Levy,2842,independent
Thomas M. Davis,138758,republican
<write in>,181,none
Thomas J. "Tom" Horton,74701,democrat
district_end
district:1
Herbert H. Bateman,165574,republican
<write in>,1661,none
district_end
year_end
year:1999
district:7
Bradley E. Evans,20293,independent
<write in>,552,none
Tom Bliley,77044,republican
district_end
district:2
<write in>,4116,none
Owen B. Pickett,67975,democrat
district_end
district:6
<write in>,66,none
Bob Goodlatte,89177,republican
David A. Bowers,39487,democrat
district_end
district:5
<write in>,785,none
Virgil H. Goode, Jr.,73097,democrat
district_end
district:8
<write in>,390,none
Demaris H. Miller,48352,republican
James P. Moran,97545,democrat
district_end
district:10
Robert A. Buchanan,4506,independent
Cornell W. Brooks,36476,democrat
Frank R. Wolf,103648,republican
<write in>,125,none
district_end
district:9
<write in>,45,none
J. A. "Joe" Barta,55918,republican
Rick Boucher,87163,democrat
district_end
district:3
Robert C. Scott,48129,democrat
<write in>,772,none
Robert S. "Bob" Barnett,14453,independent
district_end
district:11
Thomas M. Davis,91603,republican
<write in>,1701,none
C. W. "Levi" Levy,18807,independent
district_end
district:4
<write in>,2016,none
Norman Sisisky,64563,democrat
district_end
district:1
Josh Billings,9492,independent
Bradford L. Philips,13235,independent
Herbert H. Bateman,76474,republican
<write in>,856,none
district_end
year_end
year:2011
district:9
H. Morgan Griffith,95726,republican
<write in>,166,none
Rick Boucher,86743,democrat
Jeremiah D. Heaton,4282,independent
district_end
district:5
<write in>,185,none
Thomas S. P. Perriello,110562,democrat
Jeffrey A. Clark,4992,independent
Robert Hurt,119560,republican
district_end
district:10
<write in>,229,none
Jeffery R. Barnett,72604,democrat
William B. Redpath,4607,libertarian
Frank R. Wolf,131116,republican
district_end
district:1
Robert J. Wittman,135564,republican
G. Gail "for Rail" Parker,2544,independent green
Krystal M. Ball,73824,democrat
<write in>,304,none
district_end
district:2
E. Scott Rigell,88340,republican
Kenny E. Golden,7194,independent
<write in>,164,none
Glenn C. Nye,70591,democrat
district_end
district:8
James P. Moran,116404,democrat
J. Patrick Murray,71145,republican
J. Ron Fisher,2707,independent green
<write in>,492,none
district_end
district:4
Wynne V. E. LeGrow,74298,democrat
J. Randy Forbes,123659,republican
<write in>,432,none
district_end
district:11
Christopher F. DeCarlo,1846,independent
David William Gillis, Jr.,959,independent green
Gerald E. Connolly,111720,democrat
David L. Dotson,1382,libertarian
Keith S. Fimian,110739,republican
<write in>,305,none
district_end
district:3
<write in>,171,none
James J. Quigley,2383,libertarian
C. L. "Chuck" Smith, Jr.,44553,republican
Robert C. "Bobby" Scott,114754,democrat
John D. Kelly,2039,independent
district_end
district:6
Stuart M. Bain,15309,libertarian
<write in>,2709,none
Jeffrey W. Vanke,21649,independent
Bob Goodlatte,127487,republican
district_end
district:7
Eric Cantor,138209,republican
Rick E. Waugh,79616,democrat
<write in>,413,none
Floyd C. Bayne,15164,independent green
district_end
year_end
year:2017
district:1
Glenda Gail Parker,12866,independent
<write in>,737,none
Robert J. Wittman,230213,republican
M. D. "Matt" Rowe,140785,democrat
district_end
district:3
Robert C. "Bobby" Scott,208337,democrat
<write in>,714,none
M. L. "Marty" Williams,103289,republican
district_end
district:4
<write in>,789,none
Michael L. "Mike" Wade,145731,republican
A. Donald McEachin,200136,democrat
district_end
district:5
Jane D. Dittmar,148339,democrat
<write in>,659,none
Tom A. Garrett Jr.,207758,republican
district_end
district:2
Scott W. Taylor,190475,republican
Shaun D. Brown,119440,democrat
<write in>,652,none
district_end
district:9
Janice Allen Boyd,9050,independent
H. Morgan Griffith,212838,republican
Derek W. Kitts,87877,democrat
<write in>,549,none
district_end
district:7
Eileen M. Bedell,160159,democrat
<write in>,947,none
Dave Brat,218057,republican
district_end
district:10
Barbara Comstock,210791,republican
<write in>,1580,none
LuAnn L. Bennett,187712,democrat
district_end
district:8
Julio Gracia,14664,independent
Charles A. Hernick,98387,republican
<write in>,972,none
Donald S. Beyer Jr.,246653,democrat
district_end
district:6
<write in>,768,none
Kai E. Degner,112170,democrat
Bob Goodlatte,225471,republican
district_end
district:11
Gerald E. Connolly,247818,democrat
<write in>,34185,none
district_end
year_end
year:2007
district:5
<write in>,99,none
Virgil H. Goode, Jr.,125370,republican
Al C. Weed II,84682,democrat
Joseph P. Oddo,1928,independent green
district_end
district:6
Bob Goodlatte,153187,republican
<write in>,948,none
Barbara Jean Pryor,25129,independent
Andre D. Peery,24731,independent
district_end
district:2
Philip J. Kellam,83901,democrat
Thelma D. Drake,88777,republican
<write in>,481,none
district_end
district:7
W. Brad Blanton,4213,independent
<write in>,272,none
Eric Cantor,163706,republican
James M. Nachman,88206,democrat
district_end
district:10
Wilbur N. Wood III,2107,libertarian
<write in>,194,none
Neeraj C. Nigam,1851,independent
Judy M. Feder,98769,democrat
Frank R. Wolf,138213,republican
district_end
district:1
Jo Ann Davis,143889,republican
Shawn M. OÂDonnell,81083,democrat
Marvin F. Pixton III,3236,independent
<write in>,326,none
district_end
district:4
J. Randy Forbes,150967,republican
<write in>,886,none
Albert P. Burckard, Jr.,46487,independent green
district_end
district:3
<write in>,5448,none
Robert C. Scott,133546,democrat
district_end
district:9
C. W. ÂÂBillÂÂ Carrico,61574,republican
<write in>,136,none
Rick Boucher,129705,democrat
district_end
district:11
<write in>,259,none
Ferdinando C. Greco,2042,independent green
Tom Davis,130468,republican
Andrew L. Hurst,102511,democrat
district_end
district:8
James T. ÂÂJimÂÂ Hurysz,6094,independent
<write in>,476,none
James P. Moran,144700,democrat
Tom M. OÂDonoghue,66639,republican
district_end
year_end
year:2003
district:6
Bob Goodlatte,105530,republican
<write in>,3202,none
district_end
district:3
Robert C. Scott,87521,democrat
<write in>,3552,none
district_end
district:7
Ben L. "Cooter" Jones,49854,democrat
<write in>,153,none
Eric Cantor,113658,republican
district_end
district:9
J. Katzen,52076,none
<write in>,32,none
Rick Boucher,100075,democrat
district_end
district:4
J. Randy Forbes,108733,republican
<write in>,2308,none
district_end
district:11
<write in>,1027,none
Tom Davis,135379,republican
Frank W. Creel,26892,constitution
district_end
district:10
John B. Stevens Jr.,45464,democrat
<write in>,234,none
Frank R. Wolf,115917,republican
district_end
district:8
<write in>,361,none
James P. Morgan,102759,democrat
Ronald V. Crickenberger,4558,independent
Scott C. Tate,64121,republican
district_end
district:5
<write in>,68,none
Meredith M. Richards,54805,democrat
Virgil H. Goode Jr.,95360,republican
district_end
district:2
Edward L. Schrock,103807,republican
D. C. Amarasinghe,20589,green
<write in>,450,none
district_end
district:1
Jo Ann Davis,113168,republican
<write in>,4829,none
district_end
year_end
year:2009
district:3
<write in>,7377,none
Robert C. "Bobby" Scott,239911,democrat
district_end
district:8
Mark W. Ellmore,97425,republican
James P. Moran,222986,democrat
<write in>,957,none
J. Ron Fisher,6829,independent green
district_end
district:11
Gerald E. "Gerry" Connolly,196598,democrat
<write in>,864,none
Joseph P. Oddo,7271,independent green
Keith S. Fimian,154758,republican
district_end
district:4
<write in>,405,none
J. Randy Forbes,199075,republican
Andrea R. Miller,135041,democrat
district_end
district:5
Virgil H. Goode Jr.,158083,republican
<write in>,183,none
Tom S. P. Perriello,158810,democrat
district_end
district:10
Neeraj C. Nigam,8457,independent
Judy M. Feder,147357,democrat
<write in>,526,none
Frank R. Wolf,223140,republican
district_end
district:6
<write in>,262,none
Bob Goodlatte,192350,republican
S. "Sam" Rasoul,114367,democrat
Janice Lee Allen,5413,independent
district_end
district:1
Nathan D. Larson,5265,libertarian
Bill S. Day Jr.,150432,democrat
Robert J. Wittman,203839,republican
<write in>,756,none
district_end
district:9
Rick Boucher,207306,democrat
<write in>,6264,none
district_end
district:7
<write in>,683,none
Eric Cantor,233531,republican
Anita Hartke,138123,democrat
district_end
district:2
<write in>,368,none
Glenn C. Nye III,141857,democrat
Thelma Drake,128486,republican
district_end
year_end
year:2013
district:5
John Wade Douglass,149214,democrat
Robert Hurt,193009,republican
Kenneth J. Hildebrandt,5500,independent green
<write in>,388,none
district_end
district:7
E. Wayne Powell,158012,democrat
Eric Cantor,222983,republican
<write in>,914,none
district_end
district:1
Robert J. Wittman,200845,republican
<write in>,617,none
G. Gail Parker,8308,independent green
Adam M. Cook,147036,democrat
district_end
district:8
Janet Murphy,5985,independent green
James P. Moran,226847,democrat
Jason J. Howell,10180,independent
<write in>,805,none
J. Patrick Murray,107370,republican
district_end
district:9
H. Morgan Griffith,184882,republican
<write in>,376,none
Anthony J. Flaccavento,116400,democrat
district_end
district:11
Gerald E. Connolly,202606,democrat
<write in>,788,none
Christopher F. DeCarlo,3027,independent
Mark T. Gibson,3806,independent
Chris S. Perkins,117902,republican
Peter M. Marchetti,1919,independent green
Joe F. Galdo, Jr.,2195,green
district_end
district:4
<write in>,564,none
J. Randy Forbes,199292,republican
Ella P. Ward,150190,democrat
district_end
district:10
Frank R. Wolf,214038,republican
J. Kevin Chisholm,9855,independent
<write in>,527,none
Kristin A. Cabral,142024,democrat
district_end
district:2
E. Scott Rigell,166231,republican
<write in>,443,none
Paul O. Hirschbiel, Jr.,142548,democrat
district_end
district:6
Andy B. Schmookler,111949,democrat
<write in>,666,none
Bob Goodlatte,211278,republican
district_end
district:3
<write in>,806,none
Dean J. Longo,58931,republican
Robert C. ??Bobby?? Scott,259199,democrat
district_end
year_end
year:2015
district:9
H. Morgan Griffith,117465,republican
<write in>,5938,none
William R. Carr Jr.,39412,independent
district_end
district:10
<write in>,258,none
William B. Redpath,3393,libertarian
Barbara J. Comstock,125914,republican
Dianne L. Blais,946,green
John W. Foust,89957,democrat
Brad A. Eickholt,2442,independent
district_end
district:8
Donald S. Beyer Jr.,128102,democrat
Gwendolyn J. Beck,5420,independent
Jeffrey S. Carson,4409,libertarian
Micah K. Edmond,63810,republican
<write in>,372,none
Gerard C. "Gerry" Blais III,963,green
district_end
district:11
<write in>,226,none
Gerald E. Connolly ,106780,democrat
Joe R. Galdo,1739,green
Suzanne K. Scholte,75796,republican
Marc M. Harrold,3264,libertarian
district_end
district:3
<write in>,8205,none
Robert C. "Bobby" Scott,139197,democrat
district_end
district:4
<write in>,257,none
Bo C. Brown,4427,libertarian
Elliott G. Fausz,75270,democrat
J. Randy Forbes,120684,republican
district_end
district:5
W. Lawrence Gaughan,73482,democrat
<write in>,221,none
Kenneth J. Hildebrandt,2209,green
Paul F. Jones,4298,libertarian
Robert Hurt,124735,republican
district_end
district:1
Robert J. Wittman,131861,republican
Glenda Gail Parker,5097,green
<write in>,604,none
Norman G. "Norm" Mosher,72059,democrat
district_end
district:2
Suzanne D. Patrick,71178,democrat
E. Scott Rigell,101558,republican
<write in>,324,none
district_end
district:7
David A. Brat,148026,republican
John K. "Jack" Trammell,89914,democrat
<write in>,325,none
James A. Carr Jr.,5086,libertarian
district_end
district:6
William M. "Will" Hammer,22161,libertarian
<write in>,2202,none
Elaine B. Hildebrandt,21447,green
Bob Goodlatte,133898,republican
district_end
year_end
year:2001
district:11
Robert K. McBride,4774,independent
<write in>,285,none
Thomas M. Davis,150395,republican
M. L. ÂÂMikeÂÂ Corrigan,83455,democrat
C. W. ÂÂLeviÂÂ Levy,4059,independent
district_end
district:4
Norman Sisisky,189787,democrat
<write in>,2108,none
district_end
district:3
<write in>,3226,none
Robert C. Scott,137527,democrat
district_end
district:10
Marc A. Rossi,16031,independent
Frank R. Wolf,238817,republican
<write in>,682,none
Brian M. Brown,28107,independent
district_end
district:9
Michael D. ÂÂOzÂÂ Osborne,59335,republican
<write in>,32,none
Rick Boucher,137488,democrat
district_end
district:7
<write in>,304,none
Eric I. Cantor,192652,republican
Warren A. Stewart,94935,democrat
district_end
district:1
Sharon A. Wood,9652,independent
Josh Billings,4082,independent
Lawrence A. Davies,97399,democrat
<write in>,537,none
Jo Ann S. Davis,151344,republican
district_end
district:8
Ronald V. Crickenberger,3483,independent
Demaris H. Miller,88262,republican
Richard Lee ÂÂRickÂÂ Herron,2805,independent
James P. Moran,164178,democrat
<write in>,471,none
district_end
district:5
<write in>,70,none
John W. Boyd, Jr.,65387,democrat
Virgil H. Goode, Jr.,143312,independent
Joseph S. Spence,3936,independent
district_end
district:6
<write in>,1145,none
Bob Goodlatte,153338,republican
district_end
district:2
Edward L. ÂÂEdÂÂ Schrock,97856,republican
Jody M. Wagner,90328,democrat
<write in>,145,none
district_end
year_end
